<?php
/*
FlightPath was originally designed and programmed by the 
University of Louisiana at Monroe. The original source is 
copyright (C) 2011-present by the University of Louisiana at Monroe.

FlightPath is considered "open source" under the 
GNU General Public License, version 3 or any later version. 
This covers any related files and documentation packaged with 
FlightPath. 

The license is defined in full here: http://www.gnu.org/licenses/gpl.html,
and reproduced in the LICENSE.txt file.

You may modify FlightPath's source code, but this copyright and license
notice must not be modified, and must be included with the source code.
------------------------------
*/



/**
 * Implementation of hook_init.  Gets called as soon as the module
 * is included.
 *
 */
function blank_degrees_init() {

  $db = get_global_database_handler();
  $GLOBALS["blank_degrees_db"] = $db;
  
  
}


/**
 * Implementation of hook_menu().
 * This tells other parts of FlightPath where to display links
 * to this module, and what to include in the URL.
 *
 */
function blank_degrees_menu() {
  
  $items = array();
  
  $items[] = array(
    "title" => "Degree Plan Search",
    "url" => get_module_action_u_r_l("blank_degrees"),
    "target" => "_blank",
    "description" => "Browse through available degree plans as they appear
                      in FlightPath.",
    "location" => "tools",
    "icon" => $GLOBALS["fp_system_settings"]["theme"] . "/images/popup.gif",
    "weight" => 200,
  );
    
  return $items;
}


/**
 * This implementation of hook_page_switchboard gets called whenever
 * we want to go to a particular page in this module.  Therefor, it will
 * look at REQUEST or GET or POST variables, to decide where to go.
 *
 */
function blank_degrees_page_switchboard() {
  
  $perform_action = trim(addslashes($_REQUEST["perform_action"]));
  
  // Are we in draft mode?
  if ($_SESSION["fp_draft_mode"] == "yes")
  {
    $GLOBALS["bool_use_draft"] = true;
  } else {
    $GLOBALS["bool_use_draft"] = false;
  }
  
  $blank_view = $_REQUEST["blank_view"];
  $blank_print = $_REQUEST["blank_print"];
  $blank_degree_id = $_REQUEST["blank_degree_id"];
  
  if ($blank_degree_id == "" || $blank_degree_id < 1) {
    // Meaning, no degree has been selected.  Show the
    // selection screen.
    blank_degrees_display_blank_degree_selection();
  
  }
  else 
  {
    // We have all the information we need to display a blank degree.
    blank_degrees_display_blank_degree($blank_degree_id, $blank_print, $blank_view);
  }

}



function blank_degrees_display_blank_degree($blank_degree_id, $blank_print, $blank_view) {
  
      
  // Get our global variables...
  $db = $GLOBALS["blank_degrees_db"];
  $module_action_u_r_l = get_module_action_u_r_l("blank_degrees");


  // We just want to init our catalog year correctly first...
  $temp_screen = new AdvisingScreen();
  $temp_screen->init_advising_variables();
  
  
  $student = new Student();
  $student->load_student();
  $student->student_id = "000000000";
  $student->name = "Blank Degree";
  $degree_plan = new DegreePlan($blank_degree_id);
  $degree_plan->load_descriptive_data();
  $student->catalog_year = $degree_plan->catalog_year;
  $fp = new FlightPath($student, $degree_plan);
  $screen = new AdvisingScreen("advise.php", $fp, "not_advising");
  if ($blank_view == "type")
  {
    $screen = new AdvisingScreenTypeView("advise.php", $fp, "not_advising");
    $screen->view = "type";
  }
  
  $screen->bool_blank = true;
  
  if ($blank_print == "yes")
  {
    $screen->bool_print = true;
  }
  
  
  $screen->build_screen_elements();

  
  
  
  if (!$screen->bool_print)
  {
    
    $pC .= "
  		
  		<div style='font-size: 16pt; font-weight: bold;'>
  		" . $degree_plan->get_title(true) . " (" . $degree_plan->catalog_year . "-" . ($degree_plan->catalog_year+1) . ")
  		
  		<span class='tenpt' style='font-weight: normal;'>
  				<a href='$module_action_u_r_l&blank_catalog_year=$degree_plan->catalog_year' class='nounderline'>
  				[change]
  				</a>
  		</span>
  		</div>
  	
  		<div class='hypo tenpt' style='margin: 10px 5px 10px 5px; padding: 3px;'>
  			<b>Please Note:</b>
  			This degree plan should be used for demonstrative purposes only.
  			Although efforts are made to ensure the accuracy of this 
  			system, you should confirm the status 
  			of major requirements by consulting a departmental advisor.
  			
  		</div>
  		
  				";
  }

  $pC .= $screen->display_view_options();
  $pC .= $screen->display_screen();
  
  $screen->page_content = $pC;
  $screen->page_has_search = false;
  $screen->page_hide_report_error = true;
  // send to the browser
  $screen->output_to_browser();
  
  $db->add_to_log("blank_degrees","$blank_degree_id,view:$blank_view,print:$blank_print", "" . $degree_plan->get_title() . ",$degree_plan->catalog_year");
 
  
}




function blank_degrees_display_blank_degree_selection()
{
  // Get our global variables...
  $db = $GLOBALS["blank_degrees_db"];
  $module_action_u_r_l = get_module_action_u_r_l("blank_degrees");

  
  $pC = "";
  $screen = new AdvisingScreen("", null, "not_advising");
  
  
  if ($screen->page_is_mobile) {
    $screen->add_css(get_module_path("blank_degrees") . "/css/mobile.css");
  }
  
  
  $settings = $db->get_flightpath_settings();
  $current_catalog_year = $settings["current_catalog_year"];
  if ($GLOBALS["bool_use_draft"] == true)
  {
    $current_catalog_year = $settings["current_draft_catalog_year"];
  }

  //var_dump($settings);

  if ($_REQUEST["blank_catalog_year"] == "")
  {
    $_REQUEST["blank_catalog_year"] = $current_catalog_year;
  }




  $pC .= $screen->draw_curved_title("Degree Plan Search");
  $pC .= "
			<br>
			You may use this system to view degree plans as they
			will appear in FlightPath.
			<br><br>";

  if ($GLOBALS["bool_use_draft"] == true)
  {
    $pC .= "<div class='hypo tenpt'>Now viewing in <b>Draft</b> mode.</b></div>";
  }
  
  $pC .= "<form action='$module_action_u_r_l' method='get'>
          <input type='hidden' name='n' value='blank_degrees'>";
  // Has the user selected a catalog year?  If not, ask for that first.
  if ($_REQUEST["blank_catalog_year"] == "select")
  {
    $pC .= "Please select an available catalog year from the
			list below.<br><br>
			<table align='center'>
			<td width='150' valign='bottom'>
				<select name='blankCatalogYear'>";
    for ($t = $current_catalog_year; $t >= 2006; $t--)
    {
      $pC .= "<option value='$t'>$t - " . ($t+1) . "</option> \n";

    }
    $pC .= "</select>
			</td>
			<td valign='bottom'>
				<input type='submit' value='Select ->'>
			</td>
			</table>";				
  } else {
    // Catalog year HAS been selected.  So now get a degree...

    $pC .= "<input type='hidden' name='blankCatalogYear' value='{$_REQUEST["blank_catalog_year"]}'>
					";
    $pC .= "<b>Catalog year: {$_REQUEST["blank_catalog_year"]}-" . ($_REQUEST["blank_catalog_year"] + 1) . "</b>
				<span class='tenpt'>
				  <a href='$module_action_u_r_l&blank_catalog_year=select' class='nounderline'>[change]</a>
				</span>
				<br><br>
				Select a degree in {$_REQUEST["blank_catalog_year"]}-" . ($_REQUEST["blank_catalog_year"] + 1) . ": ";
    
    if (!$screen->page_is_mobile) {
      $pC .= "
				<br>
				<select name='blankDegreeID' style='width: 90%'>
					<option value=''>- Please select -</option>
					<option value=''>--------------------------</option>\n
					";
    }
    if ($degree_array = $db->get_degrees_in_catalog_year($_REQUEST["blank_catalog_year"], true, $GLOBALS["bool_use_draft"], FALSE))
    {
      foreach($degree_array as $major_code => $value)
      {
        if (trim($value["title"]) == ""){continue;}
        $degree_id = $value["degree_id"];
        $title = $value["title"];
        if ($value["degree_class"] == "G") {
          $title = "(Graduate) " . $title;
        }
        // if title is too long, shorten it.
        $maxlen = 95;
        if (strlen($title) > $maxlen)
        {
          $title = substr($title, 0, $maxlen - 3) . "...";
        }
        if (!$screen->page_is_mobile) {
          $pC .= "<option value='$degree_id'>$title</option> \n";
        }
        else {
          // We are on a mobile browser.
          $pC .= "<a class='degree-search-degree-row'
                    href='$module_action_u_r_l&blank_degree_id=$degree_id&blank_catalog_year={$_REQUEST["blank_catalog_year"]}'>
                      <div class='degree-search-degree-title'>$title</div>
                  </a>";
        }
        
      }
    }

    if (!$screen->page_is_mobile) {
      $pC .= "</select>
		
				<input type='submit' value='Select ->'>";
    }


  }


  $pC .= "</form>";

  $screen->page_content = $pC;
  $screen->page_has_search = false;
  $screen->page_hide_report_error = true;
  // send to the browser
  $screen->output_to_browser();
}
