<?php

/**
 * Implementation of hook_menu 
 */
function blank_degrees_menu() {
  
  $items = array();
  
  $items["tools/blank-degrees"] = array(
    "title" => "Blank Degree Search",
    "description" => "Browse through available degree plans as they appear in " . variable_get("system_name", "FlightPath"),
    "page_callback" => "fp_render_form",
    "page_arguments" => array("blank_degrees_select_degree_form"),
    "access_arguments" => array('access_blank_degrees'),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "target" => "_blank",
    ),    
    "type" => MENU_TYPE_NORMAL_ITEM,
    "weight" => 10,
  );
  
  $items["blank-degrees/display"] = array(
    "title" => "Blank Degrees - Display",
    "page_callback" => "blank_degrees_display_blank_degree",
    "access_arguments" => array('access_blank_degrees'),    
    "page_settings" => array(
      "display_currently_advising" => TRUE,
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "page_show_title" => TRUE,
      "menu_links" => array(         
        0 => array(
          "text" => "Degrees",
          "path" => "tools/blank-degrees",
          "query" => "blank_catalog_year=%BLANK_CATALOG_YEAR%&school_id=%SCHOOL_ID%",
        ),
      ),      
    ),    
    "tab_family" => "blank_degrees",    
    "type" => MENU_TYPE_TAB,
  );
    
  
  return $items;
  
}



/**
 * This is an implementation of hook_menu_handle_replacement_pattern.
 * It will search for and replace replacement patterns which we are aware of it in $str.
 */
function blank_degrees_menu_handle_replacement_pattern($str) {
  
  if (strpos($str, "%BLANK_CATALOG_YEAR%") !== 0) {
    // It contains this replacement pattern!
    $str = str_replace("%BLANK_CATALOG_YEAR%", @$_REQUEST["blank_catalog_year"], $str);
  }
  
  $school_id = 0;
  if (isset($_REQUEST['school_id'])) {
    $school_id = intval($_REQUEST['school_id']);
  }

  if (strpos($str, "%SCHOOL_ID%") !== 0) {
    // It contains this replacement pattern!
    $str = str_replace("%SCHOOL_ID%", $school_id, $str);
  }
    
  
  
  return $str;
}




/**
 * Implements hook_prereqs_get_prereq_warnings_for_course
 * 
 * For a blank degree, we don't want to worry about any warnings.
 */
function blank_degrees_prereqs_get_prereq_warnings_for_course(&$rtn, $course, $student) {
  
  if (isset($_REQUEST['blank_degree_id']) && $_REQUEST['blank_degree_id'] != '') {
    // We are on a blank degree, so remove any prereq warnings.
    $rtn = array();
  }
}



function blank_degrees_display_blank_degree() {
  global $screen, $student, $fp;
  
  $blank_degree_id = $_REQUEST["blank_degree_id"];
  $blank_catalog_year = $_REQUEST["blank_catalog_year"];
  $school_id = 0;
  if (isset($_REQUEST['school_id'])) {
    $school_id = intval($_REQUEST['school_id']);
  }  
  @$blank_print = $_REQUEST["blank_print"];
  @$blank_view = $_REQUEST["blank_view"];
    
  // If we used the word "current" for catalog_year, then find out what the current is.
  if (strtolower($blank_catalog_year) == "current") {
    $blank_catalog_year = variable_get_for_school("current_catalog_year", 2006, $school_id);    
  }

  $blank_degree = NULL;
  
  // If the blank_degree_id begins with "major_code_" then figure out the degree based on major_code.
  if (strstr($blank_degree_id, "major_code_")) {
    $blank_major_code = str_replace("major_code_", "", $blank_degree_id);
    // Okay, figure out the degree id based on the major code and catalog year.
    $db = get_global_database_handler();
    $blank_degree_id = $db->get_degree_id($blank_major_code, $blank_catalog_year);
    if (!$blank_degree_id) {
      // Couldn't be found!
      $rtn = "<br>" . t("Checking for major code: %blank_major_code, year: %blank_catalog_year
              <br><br>
              Sorry, but that major code/track combination and catalog year could not be found.  Please check your URL and try again.", array('%blank_major_code' => $blank_major_code, '%blank_catalog_year' => $blank_catalog_year));
      return $rtn;
    }
  }
  else {
    // Find out the major_code for this blank_degree_id...
    $blank_degree = new DegreePlan($blank_degree_id, NULL, TRUE);
    $blank_major_code = $blank_degree->major_code;
    // If there is a track, tack it on.
    if ($blank_degree->track_code != "") {
      if (!strstr($blank_major_code, "|")) $blank_major_code .= "|";
      $blank_major_code .= "_" . $blank_degree->track_code;
    }
    
    
  }
  
  
  $render = array();
  $render['#id'] = 'blank_degrees_display_blank_degree';
  $render['#view'] = $blank_view;
  
       
      
  // Are we in draft mode?
  if ($_SESSION["fp_draft_mode"] == "yes") {
    $GLOBALS["fp_advising"]["bool_use_draft"] = true;
  } 
  else {
    $GLOBALS["fp_advising"]["bool_use_draft"] = false;
  }  
  
  fp_add_css(fp_get_module_path("advise") . "/css/advise.css");  
  fp_add_js(fp_get_module_path("advise") . "/js/advise.js");
  
  $student = new Student();
  $student->load_student();
  $student->student_id = "000000000";
  $student->school_id = $school_id;
  $student->name = "Blank Degree";  
  $degree_plan = new DegreePlan($blank_degree_id);  
  $degree_plan->load_descriptive_data();
  $degree_plan->school_id = $school_id;
  $student->catalog_year = $degree_plan->catalog_year;
  $fp = new FlightPath($student, $degree_plan);
  $screen = new AdvisingScreen("", $fp, "not_advising");
  if ($blank_view == "type")
  {
    $screen = new AdvisingScreenTypeView("", $fp, "not_advising");
    $screen->view = "type";
  }
  
  
  
  $screen->bool_blank = TRUE;
  
  if ($blank_print == "yes")
  {
    $screen->bool_print = TRUE;
  }    
  

  $screen->build_screen_elements();

  $title = $degree_plan->title;
  if ($degree_plan->track_title != "") {
    $title .= " - " . $degree_plan->track_title;
  }
  fp_set_title($title);
  
  
  $render['#fp'] = $fp;
  $render['#degree_plan'] = $blank_degree;
  $render['#blank_catalog_year'] = $blank_catalog_year;
  $render['#screen'] = $screen;    
  $render['#student'] = $student;    
    
  $render['degree_plan_wrapper_top'] = array(
    'value' => "<div class='degree-plan-wrapper'>",
    'weight' => 100, 
  );


  $render['semester_table_start'] = array(
    'value' => "<table class='fp-semester-table'>",
    'weight' => 200,
  );

  $render['screen_display_screen'] = array(
    'value' => $screen->display_screen(),
    'weight' => 300, 
  );
        
  $render['semester_table_end'] = array(
    'value' => "</table>",
    'weight' => 400,
  );

  $render['degree_plan_wrapper_bottom'] = array(
    'value' => "</div>",
    'weight' => 500, 
  );
  
 
 

  if (user_has_permission("blank_degrees_view_url_options") && !$screen->bool_print) {
    // If the user has permissions, show them the extra URL options.  (but don't bother in print mode)
    
    $render['url_options_html'] = array(
      'value' => fp_render_c_fieldset("
              <div style='font-size: 0.85em;'>
                " . t("This degree may be linked to directly using the following URLs:") . "
                <ul>
                  <li>Internal ID for $blank_catalog_year: <a href='" . $GLOBALS["fp_system_settings"]["base_url"] . "/" . fp_url("blank-degrees/display", "blank_degree_id=$blank_degree_id&blank_catalog_year=$blank_catalog_year&school_id=$school_id", FALSE) . "'>Link</a></li>
                  <li>Major-code $blank_major_code for $blank_catalog_year: <a href='" . $GLOBALS["fp_system_settings"]["base_url"] . "/" . fp_url("blank-degrees/display", "blank_degree_id=major_code_$blank_major_code&blank_catalog_year=$blank_catalog_year&school_id=$school_id", FALSE) . "'>Link</a></li>
                  <li>Major-code $blank_major_code always <b>current</b> catalog: <a href='" . $GLOBALS["fp_system_settings"]["base_url"] . "/" . fp_url("blank-degrees/display", "blank_degree_id=major_code_$blank_major_code&blank_catalog_year=current&school_id=$school_id", FALSE) . "'>Link</a></li>
                </ul>
              </div>
             ", t("View URL Options"), TRUE, 'view-url-options-fs'),
      'weight' => 2000,
    );
    
    
  }
  
  
  
  // Add in the required "advising variables"
  //$rtn .= $screen->get_hidden_advising_variables("save_draft");
      
  // Figure out what the page's sub-tabs should be, and set them.
  $tab_array = array();
  $tab_array[0]["title"] = "Display by Year";
  $tab_array[0]["active"] = ($screen->view != "type");
  $tab_array[0]["on_click"] = "window.location=\"" . fp_url("blank-degrees/display", "blank_degree_id=$blank_degree_id&blank_catalog_year=$blank_catalog_year&blank_view=year&school_id=$school_id") . "\";";
      
  $tab_array[1]["title"] = "Display by Type";
  $tab_array[1]["active"] = ($screen->view == "type");
  $tab_array[1]["on_click"] = "window.location=\"" . fp_url("blank-degrees/display", "blank_degree_id=$blank_degree_id&blank_catalog_year=$blank_catalog_year&blank_view=type&school_id=$school_id") . "\";";

      
  fp_set_page_sub_tabs($tab_array);
  
  watchdog("blank_degrees", "User viewed blank degree: @year,@degree,@title", array("@year" => $blank_catalog_year, "@degree" => $blank_degree_id, "@title" => $title));
  
  
  return fp_render_content($render);
  
}


function blank_degrees_perm() {
  return array(
      'access_blank_degrees' => array(
        'title' => t('Access blank degrees'),
        'description' => t('This permission allows the user to view the blank degrees.'),
      ),
      "blank_degrees_view_url_options" => array(
                  "title" => t("View URL options"),
                  "description" => t("View URL options at the bottom of blank degrees.  Useful if you allow anonymous users to access blank degrees."), 
  ));
}




function blank_degrees_select_school_form() {
  $form = array();
  
  $options = schools_get_schools_for_fapi(TRUE, FALSE); // we don't need special permissions to view.
  $form['school_id'] = array(
    'type' => 'select',
    'label' => t('Please begin by selecting a school:'),
    'options' => $options,        
    'value' => @$_REQUEST['school_id'],
    'hide_please_select' => TRUE,
    'required' => TRUE,    
  );
  
  $form['from_select_school'] = array(
    'type' => 'hidden',
    'value' => 'yes',
  );
  
  $form['submit_btn'] = array(
    'type' => 'submit',
    'value' => t("Continue"),
  );
  
  return $form;
}




/**
 * This form lets the user select which degree they wish to view.
 */
function blank_degrees_select_degree_form() {
  $form = array();
  $m = 0; 
  
  $bool_show_continue = TRUE;
  
  // Are we in draft mode?
  if ($_SESSION["fp_draft_mode"] == "yes") {
    $GLOBALS["fp_advising"]["bool_use_draft"] = true;
  } 
  else {
    $GLOBALS["fp_advising"]["bool_use_draft"] = false;
  }  
  


  $school_id = 0;
  
  if (module_enabled("schools")) {  // The schools module is enabled.  We need to first ask what school we want to look at. 
    if (!isset($_REQUEST['school_id'])) {
      
      $form = blank_degrees_select_school_form();      
      return $form;
    } // not isset school_id
    
    $school_id = intval($_REQUEST['school_id']);
    
    $form['mark_current_school'] = array(      
      'value' => "<div class='current-school'>" . t("Current school: ") . "<strong>" . schools_get_school_name_for_id($school_id) . "</strong>
                     - " . l(t("Change?"), "tools/blank-degrees") . "</div>", 
    );
    
  }


  $form['school_id'] = array(
    'type' => 'hidden',
    'value' => $school_id,
  );
    
  
  @$blank_catalog_year = $_REQUEST["blank_catalog_year"];
  
  // If we used the word "current" for catalog_year, then find out what the current is.
  if (strtolower($blank_catalog_year) == "current") {
    $blank_catalog_year = variable_get_for_school("current_catalog_year", 2006, $school_id); 
  }
  
  if ($blank_catalog_year == "") {
    // The user must first select the desired catalog year.
    
    $catalog_year_options = array();
    $current_catalog_year = variable_get_for_school("current_catalog_year", 2006, $school_id);
    
    if ($GLOBALS["fp_advising"]["bool_use_draft"]) {
      $current_catalog_year = variable_get_for_school("current_draft_catalog_year", 2006, $school_id);
    }
    
    $earliest_catalog_year = variable_get_for_school("earliest_catalog_year", 2006, $school_id);
    for($t = $current_catalog_year; $t >= $earliest_catalog_year; $t--) {
      $catalog_year_options[$t] = "$t-" . ($t+1);
    }    

    $form["blank_catalog_year"] = array(
      "type" => "select",
      "label" => t("Please select a catalog year:"),
      "hide_please_select" => TRUE,
      "options" => $catalog_year_options,
      "weight" => 10,
    );
  }
  else {
    // Catalog year WAS specified.  So, ask the user to select a degree now.
    $form["blank_catalog_year"] = array(
      "type" => "hidden",
      "value" => $blank_catalog_year,
    );

    $form["mark_searching_in_year"] = array(
      "value" => t("Searching degrees in %year.", array("%year" => $blank_catalog_year . "-" . ($blank_catalog_year+1))) . "
                   " . l(t("Change?"), "tools/blank-degrees", "school_id=$school_id"),
      "weight" => 0,
    );    
    
    $school_id = 0;
    if (isset($_REQUEST['school_id'])) {
      $school_id = intval($_REQUEST['school_id']);
    }
    
    $mobile_markup = "";
    $degree_options = array();
    $db = get_global_database_handler();
    if ($degree_array = $db->get_degrees_in_catalog_year($blank_catalog_year, TRUE, $GLOBALS["fp_advising"]["bool_use_draft"], FALSE, array(1,2), $school_id)) {
      foreach($degree_array as $major_code => $value) {
        if (trim($value["title"]) == ""){continue;}
        $degree_id = $value["degree_id"];
        $title = $value["title"];
        if ($value["degree_class"] == "G") {
          $title = "(" . t("Graduate") . ") " . $title;          
        }
        // if title is too long, shorten it.
        $maxlen = 95;
        if (strlen($title) > $maxlen) {
          $title = substr($title, 0, $maxlen - 3) . "...";
        }
          
        $degree_options[$degree_id] = $title;
          

        $mobile_markup .= "<a class='degree-search-degree-row'
                    href='" . fp_url("blank-degrees/display", "blank_degree_id=$degree_id&blank_catalog_year={$_REQUEST["blank_catalog_year"]}") . "'>
                      <div class='degree-search-degree-title'>$title</div>
                  </a>";
        
        
      }
    }

    $form["blank_degree_id"] = array(
      "label" => t("Please select a degree"),
      "type" => "select",
      "options" => $degree_options,
      "weight" => 50,
    );
    
    
  }
  
  
  if ($bool_show_continue) {
    $form["submit"] = array(
      "type" => "submit",
      "prefix" => "",
      "value" => t("Continue"),
      "weight" => 100,
    );
  }
  
  
  return $form;
}
 

/**
 * Submit handler for degree selection
 */
function blank_degrees_select_degree_form_submit($form, $form_state) {
  
  
  // Are we first selecting a school?
  if (isset($form_state['POST']['from_select_school']) && $form_state['POST']['from_select_school'] == 'yes') {  
    fp_goto('tools/blank-degrees', 'school_id=' . intval($form_state['POST']['school_id']));
    return;
  }  
  
    
  
  $school_id = intval($form_state['values']['school_id']);
  
  // If all the user did was select catalog year, we need to redirect
  // back to the form with blank_catalog_year set.
  if ($form_state["values"]["blank_degree_id"] == "" && $form_state["values"]["blank_catalog_year"] != "") {
    // Go to degree selection.
    fp_goto("tools/blank-degrees", "blank_catalog_year=" . $form_state["values"]["blank_catalog_year"] . "&school_id=$school_id");
    return;
  }
  else if ($form_state["values"]["blank_degree_id"] != "" && $form_state["values"]["blank_catalog_year"] != ""){
    // Send them to the blank degree page
    
    fp_goto("blank-degrees/display", "blank_degree_id=" . $form_state["values"]["blank_degree_id"] . "&blank_catalog_year=" . $form_state["values"]["blank_catalog_year"] . "&school_id=$school_id");  
    return;
  }
  
}


