<?php

/**
 * This is our implimentatin of hook_cron().
 * It will get called as often as cron.php is accessed.
 * 
 * If cron.php gets called every 15 minutes, but I only want
 * THIS module's hook_cron() to be run once an hour, or once a day
 * at a specific time, I will need to impliment my own logic
 * to make that happen.
 * 
 */
function example_routine_module_cron() {
  
  print "\n I was called from example_routine_module's hook_cron() function! \n\n";
  
  // UNCOMMENT TO USE!
  /*
  // Include our oracle connection convenience functions.
  include_once("oracle_common_functions.php");
  
  // Connect to Banner using one of our convenience functions.
  my_oracle_connect();
  
  // Perform our population routines...
  example_routine_module_populate_subjects_table();
  example_routine_module_populate_transfer_institutions_table();
  
  
  // Tidy up by closing our oracle connection.
  oracle_close();
  */  
  
  
}



/**
 * This will populate our course_resources:subjects table, 
 * one of the "extra tables"
 * which FlightPath requires.  This looks at the relavant Banner table
 * and inserts into a mysql table which we have already set up,
 * in a table called flightpath_extra_data.subjects
 *
 */
function example_routine_module_populate_subjects_table() {
  
  global $db;
  
  
  // We must first truncate our mysql table.
  $res = $db->db_query("TRUNCATE TABLE flightpath.subjects");  
  
  // Okay, let's perform our query.
  $query = "SELECT stvsubj_code as subjectID, stvsubj_desc as title 
            FROM stvsubj 
            WHERE stvsubj_disp_web_ind = 'Y' ";
  $res = oracle_query($query) or die(oracle_error());

  while ($cur = oracle_fetch_array($res)) {
    // Okay, we now have our results.  We can insert into our mysql table!
    // (Oracle has made our array indexes all uppercase)
    $subject_id = mysql_real_escape_string($cur["SUBJECTID"]);
    $title = mysql_real_escape_string($cur["TITLE"]);
    
    // Insert!
    $db->db_query("INSERT INTO flightpath.subjects
                  (subject_id, title)
                  VALUES ('$subject_id', '$title') ");
    $c++;
  }
  
  echo("\n$c subjects imported from Banner.\n");
  
}



/**
 * Populates the course_resources:transfer_institutions table from
 * the relavent Banner tables.
 *
 */
function example_routine_module_populate_transfer_institutions_table() {

  global $db;  
  
  // We must first truncate our mysql table.
  $res = $db->db_query("TRUNCATE TABLE flightpath.transfer_institutions");  
  
  // Okay, let's perform our oracle query.
  // This will look in Banner and pick out some information we need
  // about all possible transfer institutions.
  $query = "SELECT stvsbgi_code AS institutionID, 
              stvsbgi_desc AS name, 
              sobsbgi_stat_code AS state 
            FROM stvsbgi 
            LEFT JOIN sobsbgi ON stvsbgi_code = sobsbgi_sbgi_code ";
  $res = oracle_query($query) or die(oracle_error());

  while ($cur = oracle_fetch_array($res)) {
    // Okay, we now have our results.  We can insert into our mysql table!
    // (Oracle has made our array indexes all uppercase)
    $institution_id = mysql_real_escape_string($cur["INSTITUTIONID"]);
    $name = mysql_real_escape_string($cur["NAME"]);
    $state = mysql_real_escape_string($cur["STATE"]);
    
    // Insert!
    $db->db_query("INSERT INTO flightpath.transfer_institutions
                  (institution_id, name, state)
                  VALUES ('$institution_id', '$name', '$state') ");
    $c++;
  }
  
  echo("\n$c transfer institutions imported from Banner.\n");  
  
}


?>