<?php

/**
 * @file
 * example_helper.module - Example module file
 * 
 * This file should be used as an example for how to create a new custom module.
 * 
 * Notice that we start the PHP tag, but do not close it.  This makes sure we do not
 * have white space at the end of the file.
 */



/**
 * Implementation of "hook_init".
 * 
 * Notice we replace the word "hook" with our module name.  This is how
 * FlightPath knows to find this function.
 * 
 * It will be run on every page load.
 * 
 * Documentation: http://getflightpath.com/api/flightpath/includes!hook.api.php/function/hook_init/4.x
 */
function example_helper_init() {
  
  // Add a message to the screen which all users can see
  fp_add_message(t("Example Helper is running."));
  
  // Let's also provide a link to our menu item, created in hook_menu.
  // Notice to the use of the "l" function, for "link".
  fp_add_message(l("Example Helper's Hello World link", "example-helper/hello-world")); 
  
  
}



/**
 * Implementation of hook_menu
 * 
 * This is a powerful function in FlightPath.  We use it to define which "menu" items
 * ie, URLs, are valid in FlightPath, and what permissions are required to visit those
 * URLs.
 * 
 * After creating new menu items in thos function, you MUST clear the menu cache
 * (link in the Admin Console of FlightPath).  Otherwise, FP will not be aware of your
 * new URLs.
 * 
 * Documentation: http://getflightpath.com/api/flightpath/includes!hook.api.php/function/hook_menu/4.x
 */
function example_helper_menu() {
  
  $items = array();

  $items["example-helper/hello-world"] = array(
    "title" => "Hello World!",  // Title of the URL
    "page_callback" => "example_helper_display_hello_world_page",  // What function to call when the user visits this URL
    "access_callback" => TRUE, // set to TRUE if anonymous users may view this page (no permissions required)
    "page_settings" => array(
      "page_show_title" => TRUE, // must be set to display title at the top of the page.
    ),
    "type" => MENU_TYPE_CALLBACK,  // one of several types of menu items.
  );
    
  
  return $items;  
}


/**
 * Display our Hello World page to the user.
 * 
 * This is the callback function for our example-helper/hello-world menu item.
 * Notice that we will build up our HTML for the page in a varialbe, 
 * and then RETURN it.  We do not attempt to print it out.  When we RETURN it,
 * FlightPath handles the themeing of the content, which is what we want.
 */
function example_helper_display_hello_world_page() {
  
  $rtn = '';
  
  
  $rtn .= '<b>Hello everyone!  This is a test to make sure my menu item is working.</b>
           <ul>
            <li>Notice we just type straight HTML in this page.</li>
            <li>Then, we return our result.</li>
           </ul>';
  
  
  return $rtn;
}






