<?php

/*
* The admin module for FlightPath.  Lets admins configure modules, users, etc, as well
* as all of the degree plan and course data within FlightPath.
*/
 
function admin_menu() {
  $items = array();
   
  $items["admin-tools/admin"] = array(
     "title" => "FlightPath Admin Console",
     "page_callback" => "admin_display_main",
     "access_arguments" => array("can_access_admin"),
     "tab_family" => "admin",
     "page_settings" => array(
       "page_has_search" => FALSE,
       "page_banner_is_link" => TRUE,
       "page_hide_report_error" => TRUE,
       "target" => "_blank",        
     ),     
     "type" => MENU_TYPE_TAB,
  );
  
  $items["admin/config/urgent-message"] = array(
    "title" => "Edit urgent message",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("admin_urgent_message_form", "system_settings"),
    "access_arguments" => array("can_edit_urgent_message"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(         
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),    
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin-tools/admin",    
  );     
   
   ///////////////////////////////////////////////////////
  ////////////////////// Degree Editing /////////////////// 
   
  $items["admin/degrees"] = array(
    "title" => "Degrees",
    "page_callback" => "admin_display_degrees",
    "access_arguments" => array("can_access_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),    
    "file" => menu_get_module_path("admin") . "/admin.degrees.inc",
    "type" => MENU_TYPE_TAB,
    "tab_family" => "admin_degrees",
  );
   
  $items["admin/degrees/edit-degree"] = array(
    "title" => "Edit Degree",
    "page_callback" => "admin_display_edit_degree",
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
        1 => array(
          "text" => "Back to Degrees list",
          "path" => "admin/degrees",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),   
    "file" => menu_get_module_path("admin") . "/admin.degrees.inc",
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin/degrees",
  );   
   
  $items["admin/degrees/handle-edit-degree-submit"] = array(    
    "page_callback" => "admin_handle_edit_degree_submit",
    "access_arguments" => array("can_edit_data_entry"),
    "file" => menu_get_module_path("admin") . "/admin.degrees.inc",
    "type" => MENU_TYPE_CALLBACK,
  );      
   

  $items["admin/degrees/popup-add-group"] = array(
    "title" => "Add Group",
    "page_callback" => "admin_display_degrees_popup_add_group",
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_is_popup" => TRUE,
      "page_hide_report_error" => TRUE,
    ),   
    "file" => menu_get_module_path("admin") . "/admin.degrees.inc",
    "type" => MENU_TYPE_CALLBACK,
  );     

  
  $items["admin/degrees/add-degree"] = array(
    "title" => "Add Degree",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("admin_add_degree_form"),
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
        1 => array(
          "text" => "Back to Degrees list",
          "path" => "admin/degrees",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),   
    "file" => menu_get_module_path("admin") . "/admin.degrees.inc",
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin/degrees",    
  );     
  
  $items["admin/degrees/copy-degree"] = array(
    "title" => "Copy Degree",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("admin_copy_degree_form"),
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
        1 => array(
          "text" => "Back to Degrees list",
          "path" => "admin/degrees",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),   
    "file" => menu_get_module_path("admin") . "/admin.degrees.inc",
    "type" => MENU_TYPE_CALLBACK,
    "tab_parent" => "admin/degrees",
  );     
  


   ///////////////////////////////////////////////////////
  ////////////////////// Group Editing /////////////////// 
   
  $items["admin/groups"] = array(
    "title" => "Groups",
    "page_callback" => "admin_display_groups",
    "access_arguments" => array("can_access_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),    
    "file" => menu_get_module_path("admin") . "/admin.groups.inc",
    "type" => MENU_TYPE_TAB,
    "tab_family" => "admin_groups",
  );

  $items["admin/groups/edit-group"] = array(
    "title" => "Edit Group",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("admin_edit_group_form"),
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
        1 => array(
          "text" => "Back to Groups list",
          "path" => "admin/groups",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),   
    "file" => menu_get_module_path("admin") . "/admin.groups.inc",
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin/groups",
  );     
     
     
  $items["admin/groups/popup-select-icon"] = array(
    "title" => "Select Icon",
    "page_callback" => "admin_display_groups_popup_select_icon",
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_is_popup" => TRUE,
      "page_hide_report_error" => TRUE,
    ),   
    "file" => menu_get_module_path("admin") . "/admin.groups.inc",
    "type" => MENU_TYPE_CALLBACK,
  );     
     
  $items["admin/groups/popup-edit-definition"] = array(
    "title" => "Edit Definition",
    "page_callback" => "admin_display_groups_popup_edit_definition",
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_is_popup" => TRUE,
      "page_hide_report_error" => TRUE,
    ),   
    "file" => menu_get_module_path("admin") . "/admin.groups.inc",
    "type" => MENU_TYPE_CALLBACK,
  );     

  $items["admin/groups/popup-show-group-use"] = array(
    "title" => "Group Use",
    "page_callback" => "admin_display_groups_popup_show_group_use",
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_is_popup" => TRUE,
      "page_hide_report_error" => TRUE,
    ),   
    "file" => menu_get_module_path("admin") . "/admin.groups.inc",
    "type" => MENU_TYPE_CALLBACK,
  );     

  $items["admin/groups/process-all-definitions"] = array(
    "title" => "Process all Definitions",
    "page_callback" => "fp_render_form",
    "page_arguments" => array("admin_process_all_definitions_form"),
    "access_arguments" => array("can_edit_data_entry"),
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "menu_links" => array(
        0 => array(
          "text" => "Back to main menu",
          "path" => "admin-tools/admin",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
        1 => array(
          "text" => "Back to Groups list",
          "path" => "admin/groups",
          "query" => "de_catalog_year=%DE_CATALOG_YEAR%",
        ),
      ),
    ),   
    "file" => menu_get_module_path("admin") . "/admin.groups.inc",
    "type" => MENU_TYPE_NORMAL_ITEM,
    "tab_parent" => "admin/groups",
  );     
          
     
     
  return $items;
}




/**
 * Convienence function to get semester's default regular name.
 */
function admin_get_semester_name($semester_num) {    
  
  $ar = array(t("Freshman Year"), t("Sophomore Year"), t("Junior Year"), t("Senior Year"));
  $s = $ar[$semester_num];
  if ($s == "")
  {
    $s = t("Year") . " " . ($semester_num + 1);
  }
  return $s;
}






/**
 * Get the "de_catalog_year" from the REQUEST.
 * If it's not there or invalid, pull it from our system settings.
 */
function admin_get_de_catalog_year() {
  $settings = fp_get_system_settings();
  $de_catalog_year = $_REQUEST["de_catalog_year"];
  if (!$de_catalog_year || $de_catalog_year < $settings["earliest_catalog_year"]) {
    $de_catalog_year = $settings["earliest_catalog_year"];
  }
  return $de_catalog_year;  
}


/**
 * This is an implementation of hook_menu_handle_replacement_pattern.
 * It will search for and replace replacement patterns which we are aware of it in $str.
 */
function admin_menu_handle_replacement_pattern($str) {
  
  if (strpos($str, "%DE_CATALOG_YEAR%") !== 0) {
    // It contains this replacement pattern!
    $str = str_replace("%DE_CATALOG_YEAR%", admin_get_de_catalog_year(), $str);
  }
  
  return $str;
}


function admin_perm() {
  return array(
    "can_access_admin" => array(
      "title" => t("Access administrative console"),
      "description" => t("This is a powerful permission!  This allows a 
                          user to access the 'admin console' for FlightPath."),
    ),
    "can_edit_urgent_message" => array(
      "title" => t("Edit urgent message"),
      "description" => t("The user may edit the 'Urgent Message' which appears at the top of every page, if set."),
    ),    
    "can_access_data_entry" => array(
      "title" => t("Access Data Entry"),
      "description" => t("The user can access (view) the data-entry portion of the admin console. Degree plans, groups, and courses."),
    ),
    "can_edit_data_entry" => array(
      "title" => t("Edit Data Entry"),
      "description" => t("This is a powerful permission! The user can edit degree plans, groups, and courses."),
    ),
    "can_view_advanced" => array(
      "title" => t("View advanced"),
      "description" => t("The user may see advanced information on-screen, for example, internal ID numbers for degrees and courses."),
    ),   
            
  );
} 
 

/**
 * Meant to be fed into "fp_system_settings_form()", this function
 * returns an array which will automatically save values to our "variables" table. 
 */
function admin_urgent_message_form() {
  $form = array();

  
  $form["mark" . $m++] = array(
    "type" => "markup",
    "value" => "<p>" . t("Any message you enter here will be displayed at the top of every page in the system. 
                  This is used to alert users that the system is about to be taken offline, or any other urgently-needed information.") . "</p>
                  <p>" . t("To delete this message, simple delete all the text in the box and save.") . "</p>",
  );
  
  $form["urgent_msg"] = array(
    "type" => "textarea",
    "label" => "Urgent message:",
    "value" => variable_get("urgent_msg", ""),
  );
  
  return $form;
}
 
  
/**
 * This is the "main" page for the admin module.  It's what the user
 * first sees when the click to go to the Admin page.
 */
function admin_display_main() {
  $rtn = "";

  $rtn .= "<h2>" . t("FlightPath Admin Console - Main Menu") . "</h2>";
  $rtn .= "<table class='fp-semester-table'>
           <tr>
            <td valign='top' width='50%'>
              " . fp_render_menu_block(t("System Configuration"), "admin/config") . "
            </td>
            <td valign='top' width='50%'>
            </td>
                        
           </tr>";
  $rtn .= "</table><br>"; // close table


  $settings = fp_get_system_settings();
  
  if (user_has_permission("can_access_data_entry")) {
    $rtn .= fp_render_curved_line("Data Entry");

    // TODO:  Maybe have a pulldown here of years, then use javascript to hide/show relavant groups.
    
    for ($t = $settings["current_catalog_year"] +1; $t >= $settings["earliest_catalog_year"]; $t--) {
      $rtn .= "<ul class='data-entry-for-cat data-entry-for-cat-$t'>";
      $rtn .= "<li>" . l(t("Degree plans for @year", array("@year" => $t)), "admin/degrees", "de_catalog_year=$t") . "</li>";
      $rtn .= "<li>" . l(t("Groups for @year", array("@year" => $t)), "admin/groups", "de_catalog_year=$t") . "</li>";
      $rtn .= "<li>" . l(t("Courses for @year", array("@year" => $t)), "path") . "</li>";
      $rtn .= "</ul>";
    }
    
  }
  
  
  
  
  
  
  
  
    
  return $rtn;
}




