<?php
/*
FlightPath was originally designed and programmed by the 
University of Louisiana at Monroe. The original source is 
copyright (C) 2011-present by the University of Louisiana at Monroe.

FlightPath is considered "open source" under the 
GNU General Public License, version 3 or any later version. 
This covers any related files and documentation packaged with 
FlightPath. 

The license is defined in full here: http://www.gnu.org/licenses/gpl.html,
and reproduced in the LICENSE.txt file.

You may modify FlightPath's source code, but this copyright and license
notice must not be modified, and must be included with the source code.
------------------------------
*/

/*
Lets someone search for course descriptions.
*/


function course_search_menu() {
  $items = array();
  
  $items["tools/course-search"] = array(
    "title" => "Course Search",
    "description" => "Use this tool to view course descriptions, sample syllabi, and projected course offering schedules.",
    "page_callback" => "course_search_display_search",
    "access_callback" => TRUE,
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
      "target" => "_blank",
      "menu_icon" => fp_theme_location() . "/images/book_glass_20.jpg",
    ),
    "type" => MENU_TYPE_NORMAL_ITEM,
  );
  
  $items["tools/course-search/courses"] = array(
    "title" => "Course Search",
    "page_callback" => "course_search_display_courses",
    "access_callback" => TRUE,
    "page_settings" => array(
      "page_has_search" => FALSE,
      "page_banner_is_link" => TRUE,
      "page_hide_report_error" => TRUE,
    ),
    "type" => MENU_TYPE_CALLBACK,
  );


    
  return $items;
}


/**
 * Implementation of hook_menu().
 * This tells other parts of FlightPath where to display links
 * to this module, and what to include in the URL.
 *
 */
function OLD__course_search_menu() {
  
  $items = array();
  
  $items[] = array(
    "title" => "Course Search",
    "url" => get_module_action_u_r_l("course_search"),
    "target" => "_blank",
    "description" => "Use this tool to view course descriptions,
                      sample syllabi, and projected course offering
                      schedules.",
    "location" => "tools",
    "icon" => $GLOBALS["fp_system_settings"]["theme"] . "/images/book_glass_20.jpg",
    "weight" => 100,
  );
  
  $items[] = array(
    "title" => "Edit Course Search Settings",
    "url" => get_module_action_u_r_l("course_search") . "&a=display_settings",
    "location" => "admin_console",
    "icon" => $GLOBALS["fp_system_settings"]["theme"] . "/images/book_glass_20.jpg",
    "weight" => 300,
  );  
    
  return $items;
}


function course_search_perm() {
  return array("can_administer_course_search" => array(
            "title" => "Can administer course search",
            "description" => "Users with this setting will be able
                              to modify settings for the Course Search module.",
          ),
  );
}


/**
 * Implementation of hook_init.  Gets called as soon as the module
 * is included.
 *
 */
function course_search_init() {

  $db = get_global_database_handler();
  $GLOBALS["course_search_db"] = $db;
  
  // Did the user select a "mode?"  Valid modes: advanced, none (default)
  $GLOBALS["course_search_mode"] = trim(addslashes($_REQUEST["mode"]));
  
}


/**
 * This implementation of hook_page_switchboard gets called whenever
 * we want to go to a particular page in this module.  Therefor, it will
 * look at REQUEST or GET or POST variables, to decide where to go.
 *
 */
function course_search_page_switchboard() {

  $db = $GLOBALS["course_search_db"];
  $settings = $db->get_flightpath_settings();  
  $GLOBALS["course_search_catalog_year"] = $settings["current_catalog_year"];
  
  
  $a = $_REQUEST["a"];
  
  if ($a == "get_syllabus") {
    course_search_get_syllabus();
    return;
  }
  
  if ($a == "display_settings") {
    if (!user_has_permission("can_administer_course_search")) {
      display_access_denied("Course Search Settings");
    }
    course_search_display_settings();
    return;
  }
  
  if ($a == "perform_submit_settings") {
    if (!user_has_permission("can_administer_course_search")) {
      display_access_denied("Course Search Settings");
    }
    course_search_perform_submit_settings();
    return;
  }
  
  // Has the user selected a subject?
  $subject_id = trim(addslashes($_REQUEST["subject_id"]));
  if ($subject_id != "")
  {
  	course_search_show_courses($subject_id);
  }
  else {  
    // If all else fails, go to the selection screen...
    course_search_display_search();
  }
  
}



/**
 * Save the contents of the settings for to the variables
 * table.
 *
 */
function course_search_perform_submit_settings() {
  $db = $GLOBALS["course_search_db"];
  
  $db->set_variable("course_search_avail_term_id_suffix_order", trim($_POST["avail_term_id_suffix_order"]));
  $db->set_variable("course_search_avail_term_headers", trim($_POST["avail_term_headers"]));
  $db->set_variable("course_search_avail_term_mobile_headers", trim($_POST["avail_term_mobile_headers"]));
  
  course_search_display_settings("<font color='green'>Settings successfully saved on " .date ("g:i:sa") . ".</font><br><br>");
  
}



function course_search_display_settings($msg = "") {
  $db = $GLOBALS["course_search_db"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");
    
  $pC = "";
  
  // for typing convenience...  
  $g = $GLOBALS["fp_system_settings"];
  
  $pC .= "<a class='tenpt' href='admin.php'>Back to main menu.</a><br>";
  $pC .= "<h2>Course Search Settings</h2>$msg
          Use this form to alter the various system settings for the
          Course Search module.
          <hr>
          <form action='$module_action_u_r_l' method='POST'>
          <input type='hidden' name='n' value='course_search'>
          ";
  
  // Use functions in the system module to make building this
  // for easier.
  
  $pC .= system_build_element("avail_term_id_suffix_order", "", "Available Term ID suffix order", 
                "Enter the order of term ID suffixes, so that they will display
                in the correct order in the table of available course
                offerings.  Separate by comma.
                <br>
                Ex: 60, 40, 41, 80, 81, mm", $db->get_variable("course_search_avail_term_id_suffix_order"));
  

  $pC .= system_build_element("avail_term_headers", "", "Available Term Table Headers", 
                "Enter the table headers for the available table, in the same
                order as the suffix order above.
                <br>
                Ex: Spring, May, Summer 1, Summer 2, Fall, Winter", $db->get_variable("course_search_avail_term_headers"));
                
  $pC .= system_build_element("avail_term_mobile_headers", "", "Available Term Mobile Table Headers", 
                "Enter the table headers for the available table, in the same
                order as the suffix order above, as it should be displayed
                on a mobile device.
                <br>
                Ex: Spr, May, Sum1, Sum2, Fall, Win", $db->get_variable("course_search_avail_term_mobile_headers"));

                
  $pC .= "<input type='hidden' name='a' value='performSubmitSettings'>
          <input type='submit' value='Submit'>
          </form>";
  
	$screen = new AdvisingScreen("",null,"not_advising");
	
	$screen->add_css(get_module_path("system") . "/css/style.css");
	$screen->add_css(get_module_path("course_search") . "/css/style.css");
	
	$screen->page_content = $pC;
	$screen->output_to_browser();	
  
}


/**
 * This function will actually deliver a syllabus to the user's browser
 * for download.
 *
 */
function course_search_get_syllabus() {
  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");

  
  $c = trim(mysql_real_escape_string($_REQUEST["c"]));
  $id = trim(mysql_real_escape_string($_REQUEST["id"]));
  
  $temp = split("_", $c);
  $subject_id = $temp[0];
  $course_num = $temp[1];
  
  // Get the filename in question...
  $query = "select * from course_syllabi
  					where course_perm_id = '$subject_id" . "_$course_num' ";
  if ($id != "") {
    $query = "select * from course_syllabi
  					where course_id = '$id' ";
  }
  $res = $db->db_query($query);
  $cur = $db->db_fetch_array($res);
  $filename = $cur["filename"];
  
  $course_id = $cur["course_id"];
  // Get the latest subject_id and course_num for this course!
  $new_course = new Course();
  $new_course->course_id = $course_id;
  $settings = $db->get_flightpath_settings();
  $new_course->catalog_year = $settings["current_catalog_year"];
  $new_course->load_descriptive_data(false, false, true);
  
  $subject_id = $new_course->subject_id;
  $course_num = $new_course->course_num;
  
  if ($filename == "" || !file_exists("./custom/files/syllabi/$filename"))
  { // Check to make sure the src file actually exists.
    // Display a message, letting the user know it does not
    // exist.
    	$db->add_to_log("syllabus", "fail,$c");
  	course_search_display_file_not_found($subject_id, $course_num);
  	return;
  }
  
  $db->add_to_log("syllabus", "get,$c");
  
  $content_type = "application/plain";  // default, save as generic binary file.
  $temp = split("\.", $filename);
  $ext = $temp[count($temp) - 1];  // get the original file extension.
  
  // attempt to match to the correct content_type...
  if ($ext == "pdf"){	$content_type = "application/pdf"; }
  if ($ext == "doc") { $content_type = "application/msword"; }
  if ($ext == "docx") { $content_type = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"; }
  if ($ext == "txt") { $content_type = "text/plain"; }
  if ($ext == "pot") { $content_type = "application/mspowerpoint"; }
  if ($ext == "ppt") { $content_type = "application/powerpoint"; }
  if (strstr($ext,"xl")) { $content_type = "application/excel"; }
  
  
  
  
  $fn = urlencode($subject_id . "_" . $course_num . "_SAMPLE_SYLLABUS") .".$ext";  // make it a safe filename.
  $fn = str_replace("+"," ",$fn); // restore spaces from + symbols...
  
  // Give it to the browser!
  header('Content-type: ' . $content_type . '');
  header('Content-Disposition: attachment; filename="' . $fn . '"');
  readfile('./custom/files/syllabi/' . $filename . '');  
  
}




function course_search_display_file_not_found($subject_id, $course_num)
{
  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");


	// Display a message to the user about the
	// file not being found.
	
	$pC = "";
	
	$pC .= "<div style='font-size:16pt; font-weight:bold;'>File Not Found</div>
			<br>
			<div class='tenpt'>
			We're sorry, but the syllabus file for $subject_id $course_num
			could not be found on the system.  It has either
			been deleted, moved, or renamed.
			<br><br>
			This error has been logged and the appropriate personnel
			notified.
			<br><br>
			We appologize for the inconvienence.
			</div>
			";
	
		
	$screen = new AdvisingScreen("",null,"not_advising");
	$screen->page_content = $pC;
	$screen->output_to_browser();	
	
}



/**
 * Show the user their select of courses.
 */
function course_search_display_courses() {
  $rtn = "";
  
  fp_add_css(fp_get_module_path("course_search") . "/css/course_search_style.css");
  
  if (fp_screen_is_mobile()) {
    fp_add_css(fp_get_module_path("course_search") . "/css/course_search_mobile_style.css");    
  }      
  
  
  $rtn .= "";
      
  $rtn .= fp_render_curved_line("Course Search");


  $settings = fp_get_system_settings();
  $current_catalog_year = $settings["current_catalog_year"];

  // catalog_year is always just whatever the current year is.
  $catalog_year = $current_catalog_year;  
  $subject_id = $_REQUEST["subject_id"];

  // Let's pull the needed variables out of our settings, so we know what
  // to query, because this is a non-FlightPath table.
  $tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["course_resources:subjects"];
  $tf = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
  $table_name_a = $tsettings["table_name"];
  
  
  $query = "SELECT DISTINCT a.* from $table_name_a a,
          courses b 
          WHERE a.$tf->subject_id = '?'
          AND a.$tf->subject_id = b.subject_id 
          AND catalog_year = '?'
          AND exclude = 0
          ORDER BY $tf->title ";
  $result = db_query($query, $subject_id, $catalog_year);
  $cur = db_fetch_array($result);
  $title = trim($cur[$tf->title]);

  $rtn .= "
  
  Current catalog year: <b>$catalog_year-" . ($catalog_year +1) . "</b>   
      ";
  $important_notice = "              
      <div class='tenpt hypo' style='padding: 5px;'>
      <b>Important Notice:</b> <ul style='margin-top: 5px;'>
      <li>Course descriptions are intended for unofficial use only.  Consult your catalog for the official listing.</li>
      <li>Anticipated course availability reflects current plans but actual offerings may change because of factors 
        unknown at planning time.  Consult the schedule of classes for final offerings.</li>
      <li>Sample syllabi are provided for planning purposes only.  The syllabus used by an instructor may vary from this sample.</li>
      <li>Please ask your advisor if you have any questions about a course.</li>
      </ul>               
      </div>
      ";

  if (fp_screen_is_mobile()) {
    // TODO:  implement the fieldset thingy.
    //$pC .= $screen->draw_c_fieldset($important_notice, "View important notice", true);   
  }
  else {
    $rtn .= $important_notice;
  }
  
  $rtn .= "      
      <div>
      
      <div style='margin: 10px 0 20px 10px; border-bottom: 2px solid black;'>
      <span style='font-size: 14pt; font-weight:bold;'>$title</span>
      " . l("[change]", "tools/course-search", "", array("class" => "nounderline")) . "      
      </div>
      ";
  // Draw the term selector.
  $only_term = $_REQUEST["only_term"];
  $rtn .= "<form id='term_form' action='" . $GLOBALS["fp_system_settings"]["base_u_r_l"] . "/tools/course-search/courses' method='GET'>           
           <input type='hidden' name='mode' value='$subject_id'>
           <input type='hidden' name='subject_id' value='$subject_id'>
           
           View courses offered:
           <select name='only_term' onChange='document.getElementById(\"term_form\").submit();'>
             <option value=''>Any term</option>
             ";
  //$term_array = array("60","mm","81","82","40","41");
  $term_array = get_term_id_suffixes();
  for ($t = $catalog_year; $t <= $catalog_year + 4; $t++)
  {
    $rtn .= "<option value=''>---------------------</option>";
    foreach($term_array as $x)
    {
      $schedule_text .= "<td class='tenpt' align='center'>";
      $the_term_id = $t . $x;
      
      //if ($x == 40 || $x == 41) {
        // Fix cat year for fall and winter.
      //  $the_term_id = ($t + 1) . $x;
    //  }
      
      $temp_course = new Course();
      $temp_course->term_id = $the_term_id;
      $term_desc = $temp_course->get_term_description(false);
      
      $sel = "";
      if ($only_term != "" && $only_term == "$the_term_id") {
        $sel = " selected";
      }
      
      $rtn .= "<option value='$the_term_id' $sel>$term_desc</option> \n";     
    }   
    
  } 
  $rtn .= "
           </select>
         </form>";
  
  if ($only_term != "") {
    $temp_course = new Course();
    $temp_course->term_id = $only_term;
    $term_desc = $temp_course->get_term_description(false);

    $rtn .= "<div style='font-weight: bold; padding-bottom: 20px;'>
             The following courses are currently scheduled to be offered during " . $term_desc . ".
            </div>";
  }
  
  
  $grad_notice_flag = false;
  $temp_course = new Course();
  // removed course_num < 500 and
  $result = db_query("SELECT * FROM courses
              WHERE `catalog_year`='?' AND
              `subject_id`='?' AND              
              `exclude`='0' ORDER BY `course_num` ", $catalog_year, $subject_id);
  if ($result)
  {
    while ($cur = db_fetch_array($result))
    {
      $n_subject_id = trim($cur["subject_id"]);
      $n_course_num = trim($cur["course_num"]);
      $n_course_id = $cur["course_id"];
      $bool_hide = FALSE;

      $title = ucwords(strtolower(trim($cur["title"])));
      // Fix formatting problems introduced by the ucwords command...

      $title = $temp_course->fix_title($title);

      $description = trim($cur["description"]);
      if ($description == "")
      {
        $description = "No description is available at this time.  Consult
              the official course catalog for listings.";
      }

      $syllabus_text = "";     
      $syllabus_array = course_search_get_course_syllabus_details("", "", $n_course_id);
      
      if ($syllabus_array["url"] != "")
      {
        $syllabus_text = "<div class='course-search-sample-syllabus'>
                          <a href='{$syllabus_array["url"]}' class='nounderline'>
                 <img src='" . fp_theme_location() . "/images/document_icon.gif' border='0' height='12'> 
                  Sample Syllabus</a>
                  
                </div>
                ";
      }

      //if ($mode == "advanced")
      //{
        // Look for all 5 years.
        $long_schedule_array = course_search_get_course_rotation_schedule($n_course_id, $catalog_year, 100, true);
      //} else {
        // Only grab next 2 years.
        $schedule_array = course_search_get_course_rotation_schedule($n_course_id, $catalog_year);  
      //}
      
      $full_schedule_array = course_search_get_course_rotation_schedule($n_course_id);
      $schedule_text = "";

      if (count($long_schedule_array) > 0)
      {
        $schedule_text .= "
              <div>
                <b>Anticipated availability:</b>
                ";
        $s_disp = "auto";
        if ($mode != "advanced")
        { // only show this in the basic mode, not advanced.
          foreach ($schedule_array as $term_id)
          {
            $temp_course = new Course();
            $temp_course->term_id = $term_id;
            $schedule_text .= " " . $temp_course->get_term_description(true) . ",";
          }
          $schedule_text = substr($schedule_text, 0, -1); // take off comma.
          $rnd_div_id = rand(1,999999);
          $schedule_text .= "
            &nbsp; | &nbsp;
            <a href='javascript: toggleHideDiv(\"$rnd_div_id\");' class='nounderline'>
              <span id='SPAN$rnd_div_id'>
                more&raquo;
                </span></a> ";
          $s_disp = "none";
        }

        // Consult our settings to find out what order our terms should be in.
        $avail_order = variable_get("course_search_avail_term_id_suffix_order");
        $term_array = explode(",", $avail_order);
        foreach ($term_array as $k => $tt) {
          $term_array[$k] = trim($tt);
        }
        
        // Get our table headers
        $avail_headers = variable_get("course_search_avail_term_headers");
        $avail_mobile_headers = variable_get("course_search_avail_term_mobile_headers");
        
        $th = explode(",", $avail_headers);
        
        $twidth = "90%";
        $mleft = "20px;";
        if (fp_screen_is_mobile()) {
          $th = explode(",", $avail_mobile_headers);
          $twidth = "100%";
          $mleft = "0";
        }
        
        $schedule_text .= "
              </div>
            <div id='$rnd_div_id' style='display: $s_disp; margin-left: $mleft;'>
            <table border='1' width='$twidth' class='fp-course-search-avail'>
              <tr>
               <td>Year</td>
              ";
        foreach ($th as $header_text) {
          $schedule_text .= "<td>" . trim($header_text) . "</td>";
        }
        $schedule_text .= "      </tr>";
        //$term_array = array("60","mm","81","82","40","41");
        for ($t = $catalog_year; $t <= $catalog_year + 4; $t++)
        {
          $schedule_text .= "<tr>
                    <td class='tenpt' align='center'>
                    <b>$t</b>
                    </td>";
          foreach($term_array as $x)
          {
            $schedule_text .= "<td class='tenpt' align='center'>";
            $the_term_id = $t . $x;
            if ($x == 40 || $x == 41) {
              // Fix cat year for fall and winter.
              $the_term_id = ($t + 1) . $x;
            }
            
            if (in_array($the_term_id, $full_schedule_array))
            {
              $schedule_text .= "<img src='" . fp_theme_location() . "/images/small_check.gif'>";             
            }
            else {
              if ($only_term != "" && $only_term == $the_term_id) {
                // Meaning, the term that the user selected is NOT in this 
                // course's schedule.  So, we should hide it.
                $bool_hide = TRUE;
              }
            }
            $schedule_text .= "&nbsp;</td>";

          }
          $schedule_text .= "</tr>";
        }


        $schedule_text .= "
            </table>
            </div>
                ";



      }
      else if ($only_term != "") {
        // This is if there are NO schedule offerings, yet the user
        // selected to view a particular term.
        $bool_hide = TRUE;
      }

      if (course_search_get_course_rotation_schedule_not_anticipated($n_course_id))
      {
        // This course has no anticipated offerings!
        $schedule_text = "<div><b>Anticipated availability:</b>
              There are no anticipated course offerings
              at this time.</div>";
        if ($only_term != "") $bool_hide = TRUE;
      }


      $min_hours = trim($cur["min_hours"]);
      $max_hours = trim($cur["max_hours"]);
      if ($min_hours == $max_hours)
      {
        $hours = $min_hours;
      } else {
        $hours = "$min_hours to $max_hours";
      }

      $repeat = "";
      if (trim($cur["repeat_hours"]) > $min_hours)
      {
        $repeat = "<div class='course-search-repeat'>May be repeated for up to {$cur["repeat_hours"]} hours of credit.</div>";
      }
      
      
      // Draw it on screen...
      if ($bool_hide != true) {     
        if ($grad_notice_flag == false && $course_num > 4999)
        {
          $grad_notice_flag = true;
          $rtn .= "<div style='font-size: 10pt; font-weight: bold;
                border-bottom: 1px solid black;
                margin-left: 10px;
                margin-bottom: 20px;
                margin-top: 50px;'>
                The following courses are for Graduate Students only.
                </div>";
        }
  
        $details = $schedule_text . $syllabus_text;

        $hyp1 = " - ";
        $on_click = "";
        if (fp_screen_is_mobile()) {
          $on_click = "on_click='toggle_course_extra(this);'";
          $hyp1 = "";
        }
        
        $rtn .= "<div class='course-search-course-block'>
                 <div class='course-search-course-title-row' 
                      $on_click>
                       <span class='course-search-course-name'>$n_subject_id $n_course_num</span>
                        $hyp1 
                        <span class='course-search-course-title'>$title</span> - $hours hrs.$repeat </div>
                 <div class='course-search-course-extra'>
                   <div class='course-search-course-description'>$description</div>
                   <div class='course-search-course-details'>$details</div>
                 </div>
                </div>
            ";
      }
  
    }
  }



  //$pC .= $screen->get_java_script_code();
  $rtn .= '    
    <script type="text/javascript">
    function toggleHideDiv(rndDivID)
    {
      var d = document.getElementById(rndDivID);
      if (d.style.display == "none")
      {
        d.style.display = "";
        document.getElementById("SPAN" + rndDivID).innerHTML = "&laquo;less";
      } else {
        d.style.display = "none";
        document.getElementById("SPAN" + rndDivID).innerHTML = "more&raquo;";
      }
      
    }
    
    function toggleCourseExtra(e) {
      $(e).siblings(".course-search-course-extra").slideToggle("medium");
    }   
    
    </script>
  
      ';

  //$db->add_to_log("course_search", "view,$subject_id,$catalog_year,$mode");

  
  return $rtn;
}



function OLD__course_search_show_courses($subject_id)
{
  
  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");
  
  
	$screen = new AdvisingScreen("",null,"not_advising");
	$pC = "";

	$screen->add_css(get_module_path("course_search") . "/css/course_search_style.css");
	if ($screen->page_is_mobile) {
	  $screen->add_css(get_module_path("course_search") . "/css/course_search_mobile_style.css");
	}
	
    
  
  	
	//add_to_log("COURSE SEARCH $subject_id $catalog_year");
	$pC .= "
         <table border='0' width='100%'>
         <tr><td class='tenpt'>

    ";
	$pC .= $screen->draw_curved_title("Course Search");
	
  // Let's pull the needed variables out of our settings, so we know what
	// to query, because this is a non-FlightPath table.
	$tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["course_resources:subjects"];
	$tf = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
	$table_name_a = $tsettings["table_name"];
	
	
	$query = "SELECT DISTINCT a.* from $table_name_a a,
					courses b 
					WHERE a.$tf->subject_id = '?'
					AND a.$tf->subject_id = b.subject_id 
					AND catalog_year = '?'
					AND exclude = 0
					ORDER BY $tf->title ";
	$result = $db->db_query($query, $subject_id, $catalog_year);
  $cur = $db->db_fetch_array($result);
	$title = trim($cur[$tf->title]);


	$pC .= "
	
	Current catalog year: <b>$catalog_year-" . ($catalog_year +1) . "</b>		
      ";
	$important_notice = "							
			<div class='tenpt hypo' style='padding: 5px;'>
			<b>Important Notice:</b> <ul style='margin-top: 5px;'>
			<li>Course descriptions are intended for unofficial use only.  Consult your catalog for the official listing.</li>
			<li>Anticipated course availability reflects current plans but actual offerings may change because of factors 
				unknown at planning time.  Consult the schedule of classes for final offerings.</li>
			<li>Sample syllabi are provided for planning purposes only.  The syllabus used by an instructor may vary from this sample.</li>
			<li>Please ask your advisor if you have any questions about a course.</li>
			</ul>								
			</div>
			";

	if ($screen->page_is_mobile) {
    $pC .= $screen->draw_c_fieldset($important_notice, "View important notice", true);	  
	}
	else {
	  $pC .= $important_notice;
	}
	
	$pC .= "			
			<div>
			
			<div style='margin: 10px 0 20px 10px; border-bottom: 2px solid black;'>
			<span style='font-size: 14pt; font-weight:bold;'>$title</span>
			<a href='$module_action_u_r_l&mode=$mode' class='nounderline'>[change]</a>			
			</div>
			";
	// Draw the term selector.
	$only_term = $_REQUEST["only_term"];
	$pC .= "<form id='term_form' action='$module_action_u_r_l' method='GET'>
	         <input type='hidden' name='n' value='course_search'>
	         <input type='hidden' name='mode' value='$subject_id'>
	         <input type='hidden' name='subject_id' value='$subject_id'>
	         
	         View courses offered:
	         <select name='only_term' onChange='document.getElementById(\"term_form\").submit();'>
	           <option value=''>Any term</option>
	           ";
  //$term_array = array("60","mm","81","82","40","41");
  $term_array = get_term_id_suffixes();
	for ($t = $catalog_year; $t <= $catalog_year + 4; $t++)
	{
	  $pC .= "<option value=''>---------------------</option>";
		foreach($term_array as $x)
		{
			$schedule_text .= "<td class='tenpt' align='center'>";
			$the_term_id = $t . $x;
			
			//if ($x == 40 || $x == 41) {
			  // Fix cat year for fall and winter.
			//  $the_term_id = ($t + 1) . $x;
		//	}
			
			$temp_course = new Course();
			$temp_course->term_id = $the_term_id;
			$term_desc = $temp_course->get_term_description(false);
			
			$sel = "";
			if ($only_term != "" && $only_term == "$the_term_id") {
			  $sel = " selected";
			}
			
			$pC .= "<option value='$the_term_id' $sel>$term_desc</option> \n";			
		}		
		
	}	
	$pC .= "
	         </select>
	       </form>";
	
	if ($only_term != "") {
		$temp_course = new Course();
		$temp_course->term_id = $only_term;
		$term_desc = $temp_course->get_term_description(false);

	  $pC .= "<div style='font-weight: bold; padding-bottom: 20px;'>
	           The following courses are currently scheduled to be offered during " . $term_desc . ".
	          </div>";
	}
	
	
	$grad_notice_flag = false;
	$temp_course = new Course();
	// removed course_num < 500 and
	$result = $db->db_query("SELECT * FROM courses
							WHERE `catalog_year`='?' AND
							`subject_id`='?' AND							
							`exclude`='0' ORDER BY `course_num` ", $catalog_year, $subject_id);
	if ($result)
	{
		while ($cur = $db->db_fetch_array($result))
		{
			$subject_id = trim($cur["subject_id"]);
			$course_num = trim($cur["course_num"]);
			$course_id = $cur["course_id"];
			$bool_hide = FALSE;

			$title = ucwords(strtolower(trim($cur["title"])));
			// Fix formatting problems introduced by the ucwords command...

			$title = $temp_course->fix_title($title);

			$description = trim($cur["description"]);
			if ($description == "")
			{
				$description = "No description is available at this time.  Consult
							the official course catalog for listings.";
			}

			$syllabus_text = "";			
			$syllabus_array = course_search_get_course_syllabus_details("", "", $course_id);
			
			if ($syllabus_array["url"] != "")
			{
				$syllabus_text = "<div class='course-search-sample-syllabus'>
				                  <a href='{$syllabus_array["url"]}' class='nounderline'>
								 <img src='$screen->theme_location/images/document_icon.gif' border='0' height='12'> 
								 	Sample Syllabus</a>
								  
								</div>
								";
			}

			//if ($mode == "advanced")
			//{
				// Look for all 5 years.
				$long_schedule_array = course_search_get_course_rotation_schedule($course_id, $catalog_year, 100, true);
			//} else {
				// Only grab next 2 years.
				$schedule_array = course_search_get_course_rotation_schedule($course_id, $catalog_year);	
			//}
			
			$full_schedule_array = course_search_get_course_rotation_schedule($course_id);
			$schedule_text = "";

			if (count($long_schedule_array) > 0)
			{
				$schedule_text .= "
							<div>
								<b>Anticipated availability:</b>
								";
				$s_disp = "auto";
				if ($mode != "advanced")
				{ // only show this in the basic mode, not advanced.
					foreach ($schedule_array as $term_id)
					{
						$temp_course = new Course();
						$temp_course->term_id = $term_id;
						$schedule_text .= " " . $temp_course->get_term_description(true) . ",";
					}
					$schedule_text = substr($schedule_text, 0, -1); // take off comma.
					$rnd_div_id = rand(1,999999);
					$schedule_text .= "
						&nbsp; | &nbsp;
						<a href='javascript: toggleHideDiv(\"$rnd_div_id\");' class='nounderline'>
							<span id='SPAN$rnd_div_id'>
								more&raquo;
								</span></a> ";
					$s_disp = "none";
				}

				// Consult our settings to find out what order our terms should be in.
				$avail_order = $db->get_variable("course_search_avail_term_id_suffix_order");
				$term_array = explode(",", $avail_order);
				foreach ($term_array as $k => $tt) {
				  $term_array[$k] = trim($tt);
				}
				
				// Get our table headers
				$avail_headers = $db->get_variable("course_search_avail_term_headers");
				$avail_mobile_headers = $db->get_variable("course_search_avail_term_mobile_headers");
				
				$th = explode(",", $avail_headers);
				
				$twidth = "90%";
				$mleft = "20px;";
				if ($screen->page_is_mobile) {
				  $th = explode(",", $avail_mobile_headers);
				  $twidth = "100%";
				  $mleft = "0";
				}
				
				$schedule_text .= "
							</div>
						<div id='$rnd_div_id' style='display: $s_disp; margin-left: $mleft;'>
						<table border='1' width='$twidth' class='fp-course-search-avail'>
							<tr>
							 <td>Year</td>
							";
				foreach ($th as $header_text) {
				  $schedule_text .= "<td>" . trim($header_text) . "</td>";
				}
				$schedule_text .= "			</tr>";
				//$term_array = array("60","mm","81","82","40","41");
				for ($t = $catalog_year; $t <= $catalog_year + 4; $t++)
				{
					$schedule_text .= "<tr>
										<td class='tenpt' align='center'>
										<b>$t</b>
										</td>";
					foreach($term_array as $x)
					{
						$schedule_text .= "<td class='tenpt' align='center'>";
						$the_term_id = $t . $x;
						if ($x == 40 || $x == 41) {
						  // Fix cat year for fall and winter.
						  $the_term_id = ($t + 1) . $x;
						}
						
						if (in_array($the_term_id, $full_schedule_array))
						{
							$schedule_text .= "<img src='$screen->theme_location/images/small_check.gif'>";							
						}
						else {
						  if ($only_term != "" && $only_term == $the_term_id) {
						    // Meaning, the term that the user selected is NOT in this 
						    // course's schedule.  So, we should hide it.
						    $bool_hide = TRUE;
						  }
						}
						$schedule_text .= "&nbsp;</td>";

					}
					$schedule_text .= "</tr>";
				}


				$schedule_text .= "
						</table>
						</div>
								";



			}
			else if ($only_term != "") {
			  // This is if there are NO schedule offerings, yet the user
			  // selected to view a particular term.
			  $bool_hide = TRUE;
			}

			if (course_search_get_course_rotation_schedule_not_anticipated($course_id))
			{
				// This course has no anticipated offerings!
				$schedule_text = "<div><b>Anticipated availability:</b>
							There are no anticipated course offerings
							at this time.</div>";
				if ($only_term != "") $bool_hide = TRUE;
			}


			$min_hours = trim($cur["min_hours"]);
			$max_hours = trim($cur["max_hours"]);
			if ($min_hours == $max_hours)
			{
				$hours = $min_hours;
			} else {
				$hours = "$min_hours to $max_hours";
			}

			$repeat = "";
			if (trim($cur["repeat_hours"]) > $min_hours)
			{
				$repeat = "<div class='course-search-repeat'>May be repeated for up to {$cur["repeat_hours"]} hours of credit.</div>";
			}
			
			
			// Draw it on screen...
			if ($bool_hide != true) {			
  			if ($grad_notice_flag == false && $course_num > 4999)
  			{
  				$grad_notice_flag = true;
  				$pC .= "<div style='font-size: 10pt; font-weight: bold;
  							border-bottom: 1px solid black;
  							margin-left: 10px;
  							margin-bottom: 20px;
  							margin-top: 50px;'>
  							The following courses are for Graduate Students only.
  							</div>";
  			}
  
  			$details = $schedule_text . $syllabus_text;

        $hyp1 = " - ";
  			$on_click = "";
  			if ($screen->page_is_mobile) {
  			  $on_click = "on_click='toggle_course_extra(this);'";
  			  $hyp1 = "";
  			}
  			
  			$pC .= "<div class='course-search-course-block'>
      					 <div class='course-search-course-title-row' 
      					      $on_click>
      					       <span class='course-search-course-name'>$subject_id $course_num</span>
      					        $hyp1 
      					        <span class='course-search-course-title'>$title</span> - $hours hrs.$repeat </div>
      					 <div class='course-search-course-extra'>
      					   <div class='course-search-course-description'>$description</div>
                   <div class='course-search-course-details'>$details</div>
                 </div>
  					    </div>
  					";
			}
  
		}
	}



	$pC .= "</td></tr></table>";


	$pC .= $screen->get_java_script_code();
	$pC .= '	  
		<script type="text/javascript">
		function toggleHideDiv(rndDivID)
		{
			var d = document.getElementById(rndDivID);
			if (d.style.display == "none")
			{
				d.style.display = "";
				document.getElementById("SPAN" + rndDivID).innerHTML = "&laquo;less";
			} else {
				d.style.display = "none";
				document.getElementById("SPAN" + rndDivID).innerHTML = "more&raquo;";
			}
			
		}
		
    function toggleCourseExtra(e) {
      $(e).siblings(".course-search-course-extra").slideToggle("medium");
    }		
		
		</script>
	
			';

	$db->add_to_log("course_search", "view,$subject_id,$catalog_year,$mode");

	$screen->page_title = "ULM FlightPath - Course Search";
	$screen->page_has_search = false;

	$screen->page_banner_is_link = true;
	$screen->page_hide_report_error = true;


	$screen->page_content = $pC;
	$screen->output_to_browser();


}



function course_search_get_course_rotation_schedule_not_anticipated($course_id)
{

  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");
  
  
  
	// Returns TRUE if not is NOT ANTICIPATED.  False, if this
	// is a normal courses which has an offering, or a blank
	// offering.  This will
	// only return true if NOTA is set as a term for this course.
	$res = $db->db_query("SELECT * FROM course_rotation_schedule
							WHERE course_id = '?'
							AND term_id = 'NOTA'
							", $course_id);
	if ($db->db_num_rows($res) > 0)
	{
		return true;
	}

	return false;

}

function course_search_get_course_rotation_schedule($course_id, $year = "", $limit = 20, $bool_include_next_five_years = false)
{
  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");

  
  // return an array containing the terms that this course
	// is going to be offered, if any.
	$rtn_array = array();
	$arr = array();
	if ($year != "")
	{ // if a year is entered, we will get the next few years, and the previous
	  // one for good measure.
		$year_line = "and (`term_id` LIKE '$year%' or `term_id` LIKE '" . ($year+1) . "%') ";
		if ($bool_include_next_five_years)
		{
			$yearm1 = $year - 1;
			$year2 = $year + 1;
			$year3 = $year + 2;
			$year4 = $year + 3;
			$year5 = $year + 4;
			$year6 = $year + 5;

			$year_line = "and (`term_id` LIKE '$year%'
							or `term_id` LIKE '$yearm1%'
							or `term_id` LIKE '$year2%'
							or `term_id` LIKE '$year3%'
							or `term_id` LIKE '$year4%'
							or `term_id` LIKE '$year5%'
							or `term_id` LIKE '$year6%'
					) ";
		}

	}


	$res = $db->db_query("SELECT * FROM course_rotation_schedule
							WHERE `course_id`='?'
							$year_line
							ORDER BY term_id
							LIMIT $limit", $course_id);
	while($cur = $db->db_fetch_array($res))
	{
		$t = $cur["term_id"];
		// Get the term from the end.
		$ss = trim(substr($t,4,1));
		if ($ss == "m"){$ss = "1.5";}
		$ss = $ss * 10;
		$year = trim(substr($t,0,4));

		// We do all this so we can establish an order to the terms
		// by using a sort() command later.
		$arr[] = $year . "~" . $ss . "~" . $t;
	}

	sort($arr);
	// Now we want to get out JUST the terms...
	foreach($arr as $line)
	{
		$temp = split("~",$line);
		$rtn_array[] = trim($temp[2]);
	}

	return $rtn_array;
}



function course_search_get_course_syllabus_details($subject_id = "", $course_num = "", $course_id = -1)
{

  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");
  
  
	// This will return an array containing information
	// about a course's syllabus, if it exists.
	$rtn_array = array();

	$server = "webservices";
	if (strstr($_SERVER["SERVER_NAME"], "orion"))
	{ // we are on production...
		$server = "orion";
	}

	// Does this course have a syllabus?
	$query = "SELECT * FROM course_syllabi
				WHERE `course_perm_id`='$subject_id" . "_$course_num'";
	if ($course_id != -1) {
	  $query = "SELECT * FROM course_syllabi
				WHERE `course_id`='$course_id' ";
	}
	
	$res = $db->db_query($query);
	$cur = $db->db_fetch_array($res);
	
	//$url = $GLOBALS["fp_system_settings"]["selfURL"] . "/" . get_module_path("course_search") . "/syllabus.php?id=" . $cur["course_id"];
	$url = get_module_action_u_r_l("course_search") . "&nosession=true&a=get_syllabus&id=" . $cur["course_id"];
	
	
	
	if ($cur["filename"] != "")
	{
		$rtn_array["url"] = $url;
		$rtn_array["filename"] = $cur["filename"];
		$rtn_array["datetime"] = $cur["datetime"];
	}


	return $rtn_array;

}




/**
 * Displays the search pulldown for the user to use to find courses.
 */
function course_search_display_search() {
    
  $rtn = "";
   
  fp_add_css(fp_get_module_path("course_search") . "/css/course_search_style.css");
  
  if (fp_screen_is_mobile()) {
    fp_add_css(fp_get_module_path("course_search") . "/css/course_search_mobile_style.css");    
  }      
  
  
  $rtn .= "";
  $rtn .= fp_render_curved_line("Course Search");


  $settings = fp_get_system_settings();
  $current_catalog_year = $settings["current_catalog_year"];
  // catalog_year is always just whatever the current year is.
  $catalog_year = $current_catalog_year;

  if ($catalog_year == "")
  {
    
    $rtn .= "Please select an available catalog year from the
      list below.<br><br>
      <form action='" . $GLOBALS["fp_system_settings"]["base_path"] . "/tools/course-search' method='GET' name='mainform' id='myform'>
      <table align='center'>
      <td width='150' valign='bottom'>
        <select name='catalog_year'>";
    for ($t = $current_catalog_year; $t >= $GLOBALS["fp_system_settings"]["earliest_catalog_year"]; $t--)
    {
      $rtn .= "<option value='$t'>$t - " . ($t+1) . "</option> \n";

    }
    $rtn .= "</select>
      </td>
      <td valign='bottom'>
        <input type='submit' value='Select ->'>
      </td>
      </table>
      </form>";

    //$db->add_to_log("course_search", "select_year");

  } 
  else {
    // Catalog year has been selected.

    $rtn .= "Current catalog year: <b>$catalog_year-" . ($catalog_year +1) . "</b>
        
        <br><br>
      Please select an available subject from the list below.<br>       
      <br>
      <form action='" . $GLOBALS["fp_system_settings"]["base_path"] . "/tools/course-search/courses' method='GET' name='mainform' id='myform'>";
    
    if (!fp_screen_is_mobile()) {
      $rtn .= "
        <div align='center'>
          <select name='subject_id' style='width: 80%;'>
        ";    
    }

    
    // Let's pull the needed variables out of our settings, so we know what
    // to query, because this is a non-FlightPath table.
    $tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["course_resources:subjects"];
    $tf = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
    $table_name_a = $tsettings["table_name"];

    $query = "SELECT DISTINCT a.* FROM $table_name_a a, courses b
          WHERE a.$tf->subject_id = b.subject_id 
          AND catalog_year = '?'
          AND exclude = 0
          ORDER BY $tf->title, subject_id";
          
    $result = db_query($query, $catalog_year);
    while ($cur = db_fetch_array($result))
    {
      $title = trim($cur[$tf->title]);
      $subject_id = trim($cur["subject_id"]);

      if (!fp_screen_is_mobile()) {
        $rtn .= "<option value='$subject_id'>$title ($subject_id)</option>";
      }
      else {
        $rtn .= "<a class='course-search-subject-select-line'
                  href='$module_action_u_r_l&mode=$mode&subject_id=$subject_id'>
                    <div class='course-search-dept-name'>$title ($subject_id)</div>
                  </a>";
      }
      
      
    }

    if (!fp_screen_is_mobile()) {
      $rtn .= "
          </select>       
          <input type='hidden' name='mode' value='$mode'>
          </div><br><br><br>
          <div align='right'>
          <input type='submit' value='Select ->'>
        </div>";
    }

    //$db->add_to_log("course_search", "select_subject");
    $rtn .= "</form>";
  
  }

  
  return $rtn;
}







function OLD__course_search_display_search()
{
  
	// Displays the search pulldown for the user to use to
	// find courses...
  // Get our global variables...
  $db = $GLOBALS["course_search_db"];
  $catalog_year = $GLOBALS["course_search_catalog_year"];  
  $mode = $GLOBALS["course_search_mode"];
  $module_action_u_r_l = get_module_action_u_r_l("course_search");
	
	
	$screen = new AdvisingScreen("",null,"not_advising");
	

	$settings = $db->get_flightpath_settings();
	$current_catalog_year = $settings["current_catalog_year"];

	$pC = "";
	
	$screen->add_css(get_module_path("course_search") . "/css/course_search_style.css");
	if ($screen->page_is_mobile) {
	  $screen->add_css(get_module_path("course_search") . "/css/course_search_mobile_style.css");
	}
	
	
	$pC .= "
         <table border='0' width='100%'>
         <tr><td class='tenpt'>
                  
         <form action='$module_action_u_r_l' method='GET' name='mainform' id='myform'>
         <input type='hidden' name='n' value='course_search'>
         
    ";
	$pC .= $screen->draw_curved_title("Course Search");


	if ($catalog_year == "")
	{
		$pC .= "Please select an available catalog year from the
			list below.<br><br>
			<table align='center'>
			<td width='150' valign='bottom'>
				<select name='catalog_year'>";
		for ($t = $current_catalog_year; $t >= $GLOBALS["fp_system_settings"]["earliest_catalog_year"]; $t--)
		{
			$pC .= "<option value='$t'>$t - " . ($t+1) . "</option> \n";

		}
		$pC .= "</select>
			</td>
			<td valign='bottom'>
				<input type='submit' value='Select ->'>
			</td>
			</table>";

		$db->add_to_log("course_search", "select_year");

	} else
	{


		$pC .= "Current catalog year: <b>$catalog_year-" . ($catalog_year +1) . "</b>
				
				<br><br>
			Please select an available subject from the list below.<br>				
			<br>";
		
		if (!$screen->page_is_mobile) {
  		$pC .= "
  			<div align='center'>
  				<select name='subject_id' style='width: 80%;'>
  			";  	
		}

		
    // Let's pull the needed variables out of our settings, so we know what
		// to query, because this is a non-FlightPath table.
		$tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["course_resources:subjects"];
		$tf = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
		$table_name_a = $tsettings["table_name"];

		$query = "SELECT DISTINCT a.* FROM $table_name_a a, courses b
					WHERE a.$tf->subject_id = b.subject_id 
					AND catalog_year = $catalog_year
					AND exclude = 0
					ORDER BY $tf->title, subject_id";

		$result = $db->db_query($query);
		while ($cur = $db->db_fetch_array($result))
		{
			$title = trim($cur[$tf->title]);
			$subject_id = trim($cur["subject_id"]);

			if (!$screen->page_is_mobile) {
			  $pC .= "<option value='$subject_id'>$title ($subject_id)</option>";
			}
			else {
			  $pC .= "<a class='course-search-subject-select-line'
			            href='$module_action_u_r_l&mode=$mode&subject_id=$subject_id'>
			              <div class='course-search-dept-name'>$title ($subject_id)</div>
			            </a>";
			}
			
			
		}

		if (!$screen->page_is_mobile) {
  		$pC .= "
  				</select>				
  				<input type='hidden' name='mode' value='$mode'>
  				</div><br><br><br>
  				<div align='right'>
  				<input type='submit' value='Select ->'>
  			</div>";
		}

		$db->add_to_log("course_search", "select_subject");

	}

	$pC .= "</td></tr></table>";

	$pC .= "</form>";



	//$pC = get_js_functions() . $pC;  // get the javascript functions for this page. (at the top)

	$screen->page_title = "ULM FlightPath - Course Search";
	$screen->page_has_search = false;

	$screen->page_banner_is_link = true;
	$screen->page_hide_report_error = true;
	$screen->page_content = $pC;
	$screen->output_to_browser();


}
