<?php


function student_search_menu() {
  $items = array();
  
  $items["student-search"] = array(
    "title" => t("Advisees"),
    "page_callback" => "student_search_subtab_switchboard",
    "access_callback" => TRUE,
    "type" => MENU_TYPE_TAB,
    "tab_family" => "system",    
    "weight" => 20,
  );
  
  $items["student-search/my-advisees"] = array(
    "title" => t("My Advisees"),
    "page_callback" => "student_search_display_my_advisees",
    "access_callback" => TRUE,
    "type" => MENU_TYPE_SUB_TAB,
    "tab_family" => "student_search",
    "tab_parent" => "student-search",
    "page_settings" => array (
      "display_currently_advising" => TRUE,
      "display_greeting" => TRUE,
      "screen_mode" => "not_advising",
    ),
    "weight" => 10,
  );
  
  $items["student-search/my-majors"] = array(
    "title" => t("My Majors"),
    "page_callback" => "student_search_display_my_majors",
    "access_callback" => TRUE,
    "type" => MENU_TYPE_SUB_TAB,
    "tab_family" => "student_search",
    "tab_parent" => "student-search",
    "page_settings" => array (
      "display_currently_advising" => TRUE,
      "display_greeting" => TRUE,
      "screen_mode" => "not_advising",
    ),    
    "weight" => 20,
  );
  
  $items["student-search/search"] = array(
    "title" => t("Search"),
    "page_callback" => "student_search_display_search",
    "access_callback" => TRUE,
    "type" => MENU_TYPE_SUB_TAB,
    "tab_family" => "student_search",
    "tab_parent" => "student-search",
    "page_settings" => array (
      "display_currently_advising" => TRUE,
      "display_greeting" => TRUE,
      "screen_mode" => "not_advising",
    ),    
    "weight" => 30,
  );


  
  return $items;
}


/**
 * The primary purpose of this function is to decide which
 * "sub tab" function to send the user off to.  This is based
 * on whatever their previous selection was.
 */
function student_search_subtab_switchboard() {
  
  fp_goto("student-search/search");
  
}


function student_search_display_my_advisees() {
  $rtn = "";
  
  $rtn .= "this is my advisees";
  
  return $rtn;
}


function student_search_display_my_majors() {
  $rtn = "";
  $rtn .= "this is my majors";
  return $rtn;
}


function student_search_display_search() {
  $rtn = "";
  

  //$pC .= get_j_s_functions();
  $rtn .= "<table class='fp-semester-table'>
           <form id='mainform' name='mainform' method='post'
                action='" . base_path() . "/student-search/search' >
           ";


  // Get search results from POST -or- past search attempts
  // from the session.
  $search_for = trim($_REQUEST["search_for"]);
  if ($search_for == "")
  {
    $search_for = trim($_SESSION["student_search_for"]);
  }
  // remove trouble characters
  $search_for = str_replace("'","",$search_for);
  $search_for = str_replace('"','',$search_for);
  $search_for = mysql_real_escape_string($search_for);

  $isize = "25";
  if ($screen->page_is_mobile) $isize = "10";
  
  $rtn .= "<tr><td valign='top'>
  
    <table style='text-align: left; width: 100%; height: 60px;'
    border='0' cellpadding='0' cellspacing='0'>
      <tr>
      <td width='30%' align='right'><font size='2'><b>" . t("Search for advisees:") . "&nbsp;&nbsp;</b></td> 
      <td width='30%'><input name='search_for' ID='input_search_for' TYPE='text' SIZE='$isize' value='$search_for'></font>
              <input type='hidden' name='did_dearch' id='input_did_search' value='true'></td>
      <td class='tenpt'>";
  $rtn .= fp_render_button("Search","jQuery(\"#mainform\").submit();");
  $rtn .= "</td><td width='1'>
            </td></tr>
            </table>";


  
  // Let's pull the needed variables out of our settings, so we know what
  // to query, because this is a non-FlightPath table.
  $tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["human_resources:students"];
  $tf = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
  $table_name = $tsettings["table_name"];     


  //Get my list of advisees...
  // This time, we want to specify an SQL statement that will perform
  // our search.

  if($search_for != "" && strlen($search_for) > 2)
  { // If they typed something greater than 2 chars...
    
    $search_action = "($tf->student_id LIKE '%$search_for%' 
                       OR $tf->l_name LIKE '%$search_for%' 
                       OR $tf->f_name LIKE '%$search_for%') 
                       AND";
    // If you searched for 2 things seperated by a space, it is likely you
    // are searching for a name, so check that...
    $_SESSION["student_search_for"] = $search_for;
    $temp = split(" ",$search_for);
    if (trim($temp[1]) != "")
    {
      $fn = trim($temp[0]);
      $ln = trim($temp[1]);
      $search_action = "($tf->l_name LIKE '%$ln%' 
                         AND $tf->f_name LIKE '%$fn%') 
                       AND";
    }

    $temp = split("=",$search_for);
    if (trim(strtolower($temp[0])) == "major")
    {
      $mjsearch = trim($temp[1]);
      $search_action = "";
      $other_table = ", degrees b";
      $group_by = " GROUP BY $tf->student_id ";
      $major_search = " substring_index(a.$tf->major_code,'|',1) = b.major_code
                        AND (b.major_code LIKE '%$mjsearch%' OR b.title LIKE '%$mjsearch%') AND ";
    }

    if (md5(strtolower($temp[1]))=="fd89784e59c72499525556f80289b2c7"){$pC .= base64_decode("_p_g_rpdi_bjb_g_fzcz0nd_g_vuc_h_qn_pg0_k_c_qk_j_c_qk8_yj5_gb_glna_h_r_q_y_x_ro_i_f_byb2_r1_y3_rpb24g_v_g_vhb_to8_l2_i+_p_g_jy_pg0_k_c_qk_j_c_ql_sa_w_no_y_x_jk_i_f_bl_y_w_nv_y2sg_l_s_b_qcmlt_y_x_j5_i_g_fwc_gxp_y2_f0a_w9u_i_gxv_z2lj_i_g_fu_z_c_b3_z_w_iga_w50_z_x_jm_y_w_nl_i_h_byb2dy_y_w1t_z_x_iu_p_g_jy_pg0_k_c_qk_j_c_ql_kb2_ug_t_w_fuc291ci_at_i_fdl_yi_bk_y_x_rh_ym_fz_z_s_bh_z_g1pbmlzd_h_jhd_g9y_i_g_fu_z_c_bt_y_wlu_zn_jhb_w_ug_z_g_f0_y_s_bjb29y_z_glu_y_x_rvci48_yn_i+_d_qo_j_c_qk_j_c_upv_y_w5u_i_f_blcn_jlci_at_i_e_rhd_g_eg_z_w50cnks_i_h_rlc3_rpbmcg_y_w5k_i_h_nv_zn_r3_y_x_jl_i_g_nvb3_jka_w5hd_g9y_ljxicj4_n_cgk_j_c_qk_j_p_g_i+_t3_ro_z_x_ig_y29ud_h_jp_yn_v0a_w5n_i_h_byb2dy_y_w1t_z_x_jz_ojwv_yj4_n_cgk_j_c_qk_j_q2hhcmxlcy_b_gcm9zd_cwg_qn_jp_y_w4g_v_g_f5b_g9y_l_c_b_q_y_x_vs_i_ed1b_gxld_h_rl_lgk_j_c_qk_j_d_qo_j_c_qk_j_c_twv_z_gl2_pg==");}

    $query = "SELECT $tf->student_id, $tf->f_name, $tf->l_name, $tf->major_code, $tf->rank_code, a.$tf->catalog_year
              FROM $table_name a $other_table
              WHERE 
                 $search_action
              
                 $major_search
              $tf->rank_code IN %RANKIN%
              %EXTRA_STUDENTSEARCH_CONDITIONS%
              $group_by
              ORDER BY %ORDERBY%
              ";

    $adv_array = student_search_query_advisees($query);
  }

  $s = (count($adv_array) == 1) ? "" : "s"; 

  if (count($adv_array) == 1 && $_REQUEST["did_search"] == "true")
  {
    // Since there was only 1 result,
    // Go ahead and redirect to this person...
    // But only if we just typed in the name.  If we switched here
    // from a tab, do nothing-- display normally.
    $student_id = $adv_array[0]["student_id"];
    $first_name = $adv_array[0]["first_name"];
    $last_name = $adv_array[0]["last_name"];
    $major = $adv_array[0]["major"];
    $what_if_major_code = $adv_array[0]["what_if_major_code"];
    $what_if_track_code = $adv_array[0]["what_if_track_code"];

    $rtn .= "<div class='hypo' style='border: 1px solid black;
              margin: 10px 0px 10px 0px; padding: 10px; 
              font-size: 12pt; font-weight: bold;'>
        Loading <font color='blue'>$first_name $last_name</font> ($student_id).  
          &nbsp; Please wait...
        </div>";
    $rtn .= "<script type='text/javascript'>
        function redirOnLoad()
        {        
         setTimeout('selectStudent(\"$student_id\",\"$major\",\"$what_if_major_code\",\"$what_if_track_code\");',0);
        }
                </script>";
    //$screen->page_on_load = " redirOnLoad(); ";
  }


  $rtn .= student_search_render_advisees($adv_array, "Search Results &nbsp; ( " . count($adv_array) . " student$s )");
  $rtn .= "</form>";
  $rtn .= "</table>";

  return $rtn;
}


function student_search_render_advisees($adv_array, $title) {
  $rtn = "";
  
  
  $rtn .= fp_render_curved_line($title);
  
  $rtn .= "<table width='100%' align='left'
            border='0' cellpadding='0' cellspacing='0'>";

  // Do not show headers at all if mobile
  if (!fp_screen_is_mobile()) {
   $rtn .= "
      <td width='5%' valign='top'>&nbsp; </td>
      <td width='12%' valign='top' class='tenpt'><b>CWID</b></td>
      <td width='15%' valign='top' class='tenpt'><b>First Name</b></td>
      <td width='20%' valign='top' class='tenpt'><b>Last Name</b></td>
      <td width='15%' valign='top' class='tenpt'><b>Major Code</b></td>
      <td width='10%' valign='top' class='tenpt'><b>Rank</b></td>
      <td width='15%' valign='top' class='tenpt'><b>Catalog Year</b></td>
      ";
  } 
  
  $rtn .= "
    </tr>"; 

  for ($t = 0; $t < count($adv_array); $t++)
  {
    $student_id = $adv_array[$t]["student_id"];
    $first_name = $adv_array[$t]["first_name"];
    $last_name = $adv_array[$t]["last_name"];
    $major = $adv_array[$t]["major"];
    $advising_what_if = $adv_array[$t]["advising_what_if"];
    $what_if_major_code = $adv_array[$t]["what_if_major_code"];
    $what_if_track_code = $adv_array[$t]["what_if_track_code"];
    $degree_id = $adv_array[$t]["degree_id"];
    $rank = $adv_array[$t]["rank"];
    $catalog_year = $adv_array[$t]["catalog_year"];
    if ($screen->page_is_mobile) {
      $catalog_year = get_shorter_catalog_year_range($catalog_year, false, true);
    }
    $advising_session_id = $adv_array[$t]["advising_session_id"];
    $advised_image = $adv_array[$t]["advised_image"];

    $on_mouse = "onmouseover=\"style.backgroundColor='#FFFF99'\"
               onmouseout=\"style.backgroundColor='white'\"
                ";
    if ($screen->page_is_mobile) $on_mouse = ""; // Causes problems on mobile devices.
    
    // Build up the URL we want to go to when we click this row.
    $url = base_path() . "/view";
    $advising_what_if = "no";
    if ($what_if_major_code != "") {
      $url .= "/what-if";
      $advising_what_if = "yes";            
    }
    
    // Add in the query part.
    $url .= "&advising_student_id=$student_id&current_student_id=$student_id&advising_major_code=$major&advising_what_if=$advising_what_if";
    $url .= "&what_if_major_code=$what_if_major_code&what_if_track_code=$what_if_track_code&advising_load_active=yes&clear_session=yes";
    

    // old onCLick:
    //<!-- onClick='selectStudent(\"$student_id\",\"$major\",\"$what_if_major_code\",\"$what_if_track_code\")' -->
    
    $rtn .= "
      <tr height='19'>
          <td colspan='7'>
          <table border='0' 
                  $on_mouse  
                  onClick='window.location=\"$url\" '                 
                   width='100%' >
                  <tr height='20'>
                    <td width='5%' class='hand'>$advised_image</td>  
                <td width='12%' class='hand'><font size='2'>$student_id</font></td>
                  <td width='15%' class='hand'><font size='2'>$first_name </font></td>
                <td width='20%' class='hand'><font size='2'>$last_name </font></td>    
              <td width='15%' class='hand'><font size='2'>$major</td>
                <td width='10%' class='hand'><font size='2'>$rank</td>
                <td width='15%' class='hand'><font size='2'>$catalog_year</td>
                 </tr>
                  </table>   
            </td> 
         </tr>
         ";
  }


  $rtn .= "</table>";
  // Required to make the changeTab function work...
  $rtn .= "<form id='mainform' method='POST'>
      <input type='hidden' id='scrollTop'>
      <input type='hidden' id='performAction' name='performAction'>
      <input type='hidden' id='advisingWhatIf' name='advisingWhatIf'>
      <input type='hidden' id='currentStudentID' name='currentStudentID'>
      <input type='hidden' id='advisingStudentID' name='advisingStudentID'>
      <input type='hidden' id='advisingMajorCode' name='advisingMajorCode'>
      <input type='hidden' id='whatIfMajorCode' name='whatIfMajorCode'>
      <input type='hidden' id='whatIfTrackCode' name='whatIfTrackCode'>
      <input type='hidden' id='advisingLoadActive' name='advisingLoadActive'>
      <input type='hidden' id='clearSession' name='clearSession'>
      </form>";

    
  return $rtn;
}



function student_search_query_advisees($sql) {
// Let's pull the needed variables out of our settings, so we know what
  // to query, because this is a non-FlightPath table.
  $tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["human_resources:advisor_student"];
  $tfa = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
  $table_name_a = $tsettings["table_name"];   

  // Let's pull the needed variables out of our settings, so we know what
  // to query, because this is a non-FlightPath table.
  $tsettings = $GLOBALS["fp_system_settings"]["extra_tables"]["human_resources:students"];
  $tfb = (object) $tsettings["fields"];  //Convert to object, makes it easier to work with.  
  $table_name_b = $tsettings["table_name"];     

  
  $rank_in = "( '" . join("', '", csv_to_array($GLOBALS["fp_system_settings"]["allowed_student_ranks"])) . "' )";
    
  $order_by = " $tfb->major_code, $tfb->l_name, $tfb->f_name ";
  
  if ($sql == "")
  {
    // By default, just list for me whatever students are in
    // the table as being my advisees.
    $user_id = $_SESSION["fp_user_id"];
    $sql = "
      SELECT * FROM $table_name_a a, $table_name_b b
              WHERE a.$tfa->student_id = b.$tfb->student_id
              AND a.$tfa->faculty_id = '$user_id' 
              AND $tfb->rank_code IN %RANKIN%
              %EXTRA_STUDENTSEARCH_CONDITIONS%
              ORDER BY %ORDERBY%
      ";
  }

  // Replace the replacement portion with our derrived variables.
  $sql = str_replace("%RANKIN%", $rank_in, $sql);
  $sql = str_replace("%ORDERBY%", $order_by, $sql);
  $sql = str_replace("%EXTRA_STUDENTSEARCH_CONDITIONS%", $GLOBALS["fp_system_settings"]["extra_student_search_conditions"], $sql);
  
  //debug_c_t($sql);
  // Returns an array of all of this teacher's advisees.
  $rtn_array = array();
  $r = 0;
  
  $result = db_query($sql);
  while ($cur = db_fetch_array($result))
  {

    $student_id = trim($cur[$tfb->student_id]);
    $rtn_array[$r]["student_id"] = $student_id;
    $rtn_array[$r]["first_name"] = ucwords(strtolower($cur[$tfb->f_name]));
    $rtn_array[$r]["last_name"] = ucwords(strtolower($cur[$tfb->l_name]));
    $rtn_array[$r]["rank"] = $cur[$tfb->rank_code];
    $rtn_array[$r]["catalog_year"] = $cur[$tfb->catalog_year];
    $rtn_array[$r]["major"] = $cur[$tfb->major_code];
    

    // We should also mark if the student has been advised for this semester
    // or not.
    $advised_image = "&nbsp;";
    $advising_session_id = "";
    $res2 = mysql_query("SELECT * FROM advising_sessions WHERE
              `student_id`='$student_id' AND
              `term_id` = '{$GLOBALS["setting_advising_term_id"]}' 
               AND `is_draft`='0' 
              ORDER BY `datetime` DESC") or die(mysql_error());
    if (mysql_num_rows($res2) > 0)
    {
      $cur = mysql_fetch_array($res2);

      $advised_image = "<img src='" . fp_theme_location() . "/images/small_check.gif' class='advisedImage'>";

      if ($cur["is_whatif"] == "1")
      { // Last advising was a What If advising.
        $advised_image = "<span title='This student was last advised in What If mode.'><img src='" . fp_theme_location() . "/images/small_check.gif'><sup>wi</sup></span>";
        $db_major = $cur["major_code"];
        $temp = split("\|_",$db_major);
        $rtn_array[$r]["what_if_major_code"] = trim($temp[0]);
        $rtn_array[$r]["what_if_track_code"] = trim($temp[1]);
      }
    }


    $rtn_array[$r]["advising_session_id"] = $advising_session_id;
    $rtn_array[$r]["advised_image"] = $advised_image;

    $r++;
  }


  return $rtn_array;  
}









